OHRM5x-533 - Project list backend API
orangehrm/orangehrm pull request #1036
Opened 2021-12-02 21:34 UTC by SandeepaOHRM

This PR includes,

- create endpoint
- getAll endpoint with filters
- getOnce endpoint
- update endpoint
- delete endpoint

This PR doesn't include

- Unit testings
- Frontend codebase for project

2021-12-06 07:09 UTC, RajithaKumara requested changes

2021-12-06 07:09 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/entity/Project.php
> +     */
```suggestion
    /**
     * @var string|null
     *
     * @ORM\Column(name="name", type="string", length=100)
     */
```
preferred this pattern for all other attribute annotations. (proper spacing)

2021-12-06 07:09 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/entity/Project.php
> +    private Collection $projectAdmins;
```suggestion
    /**
     * @ORM\ManyToMany(targetEntity="OrangeHRM\Entity\Employee")
     * @ORM\JoinTable(name="ohrm_project_admin",
     *      joinColumns={@ORM\JoinColumn(name="project_id", referencedColumnName="project_id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="emp_number", referencedColumnName="emp_number")}
     * )
     */
    private iterable $projectAdmins;
```

2021-12-06 07:09 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/test/Api/ProjectAPITest.php
> +class ProjectAPITest extends EndpointTestCase
please continue with `EndpointIntegrationTestCase`. e.g. `symfony/plugins/orangehrmLeavePlugin/test/Api/MyLeaveRequestAPITest.php`

2021-12-06 07:09 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/test/Entity/ProjectTest.php
> +        TestDataService::truncateTables([Project::class]);
Seems you used deprecated method. use `truncateSpecificTables` instead

2021-12-08 03:19 UTC, SandeepaOHRM commented on symfony/plugins/orangehrmTimePlugin/entity/Customer.php
> +     * @ORM\OneToMany (targetEntity="OrangeHRM\Entity\Project", mappedBy="customer")
for unit testing it requied to have mappedBy attribute

2021-12-08 06:15 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/Project.vue
> +<style lang="scss" scoped></style>
Remove empty tag

2021-12-08 06:26 UTC, Super-Chama requested changes
Please make sure all string are using translation strings and run `yarn lint` to get rid of lint issues.

2021-12-08 06:26 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/Project.vue
> +<style lang="scss" scoped></style>
Remove empty tag

2021-12-08 06:26 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/Project.vue
> +          <oxd-button displayType="ghost" label="Reset" @click="onClickReset" />
without `@click="onClickReset"` you can simply use `type="reset"`

2021-12-08 06:26 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/Project.vue
> +          <oxd-button
use `submit-button` component with `:label="$t('general.search')"`

2021-12-08 06:26 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/Project.vue
> +          <oxd-button displayType="ghost" label="Reset" @click="onClickReset" />
use translation string for label

2021-12-08 06:26 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/Project.vue
> +    <oxd-table-filter filter-title="Projects">
Use translation for title

2021-12-08 06:26 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/Project.vue
> +
remove space

2021-12-08 06:26 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/project.scss
> +// OrangeHRM is a comprehensive Human Resource Management (HRM) System that captures
seems this file is unused. if so remove it

2021-12-08 08:16 UTC, RajithaKumara approved these changes

2021-12-08 08:16 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/Api/ProjectAPI.php
> +    public const PARAMETER_IS_DELETED = 'isDeleted';
can remove this

2021-12-08 08:16 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/Api/ValidateProjectNameAPI.php
> +                self::PARAMETER_IS_CHANGEABLE=> $isChangeableProjectName
format the code

2021-12-08 08:16 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/Api/ValidateProjectNameAPI.php
> +    public function getOne(): EndpointResult
add doc comments for all methods

2021-12-08 08:16 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/entity/Decorator/ProjectAdminDecorator.php
> +    //empNumber
remove this comment

2021-12-08 08:16 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/entity/Decorator/ProjectAdminDecorator.php
> +    public function setProject($id): void
```suggestion
    public function setProjectById(int $id): void
```
+ missing doc comment

2021-12-08 08:16 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/entity/Decorator/ProjectAdminDecorator.php
> +    }
why we need this?

2021-12-08 08:16 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/entity/Project.php
> +    public function getIsDeleted(): bool
```suggestion
    public function isDeleted(): bool
```

2021-12-08 08:16 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/entity/Project.php
>      public function setIsDeleted(bool $isDeleted): void
```suggestion
    public function setDeleted(bool $isDeleted): void
```

2021-12-09 10:32 UTC, Super-Chama requested changes
Please correct these issues and earlier issues

2021-12-09 10:32 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/components/AddCustomerModal.vue
> +                customerName: this.customer.name.trim(),
use the passed parameter for validation. `customer`

2021-12-09 10:32 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/components/AddCustomerModal.vue
> +      this.$emit('close');
define [emits](https://v3.vuejs.org/api/options-data.html#emits). make sure to get latest and run yarn lint

2021-12-09 10:32 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/components/AddCustomerModal.vue
> +<style lang="scss" scoped></style>
remove empty style tag

2021-12-09 10:32 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/components/ProjectAdminInput.vue
> +  name: 'project-admin-input',
`project-admin-autocomplete` would be proper name since this input is wrapping autocomplete

2021-12-09 10:32 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/ProjectEdit.vue
> +                style=""
remove `style=""`

2021-12-09 10:32 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/ProjectEdit.vue
> +                style=""
remove `style=""`

2021-12-09 10:32 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/ProjectEdit.vue
> +      console.log(this.projectAdmins);
no `console.log()`

2021-12-09 10:32 UTC, Super-Chama commented on symfony/client/src/orangehrmTimePlugin/pages/project/ProjectEdit.vue
> +    // validateProjectName(project) {
no commented code

2021-12-10 03:50 UTC, RajithaKumara approved these changes

2021-12-10 04:10 UTC, merged