OHRM5X-976: Project Activity unique name validation API added
orangehrm/orangehrm pull request #1064
Opened 2021-12-23 09:11 UTC by VageeshOrangeHRM

This PR Contains following changes:
1. Unique validation added for project activity name.
2. Unit test added for the API.
3. Data group permission added for the API.
4. Unit test covered for customer DAO layer.

2021-12-23 17:08 UTC, RajithaKumara requested changes

2021-12-23 17:08 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/Dao/ProjectActivityDao.php
> +    public function isProjectNameTaken(int $projectId, string $projectActivityName, ?int $projectActivityId = null): bool
```suggestion
    public function isProjectActivityNameTaken(int $projectId, string $projectActivityName, ?int $projectActivityId = null): bool
```

2021-12-24 03:14 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Dao/ProjectActivityDao.php
> +        return $this->getPaginator($q)->count() === 0;
done

2021-12-24 03:14 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Api/ValidationProjectActivityNameAPI.php
> +        $isChangeableProjectActivityName = $this->getProjectActivityService()
done

2021-12-24 03:14 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Dao/ProjectActivityDao.php
> +    public function isProjectNameTaken(int $projectId, string $projectActivityName, ?int $projectActivityId = null): bool
done

2021-12-24 03:55 UTC, RajithaKumara approved these changes

2021-12-24 03:55 UTC, RajithaKumara commented on symfony/plugins/orangehrmAdminPlugin/test/Dao/UserDaoTest.php
>          $this->assertEquals(false, $status);
```suggestion
        $status = $this->systemUserDao->isUserNameExistByUserName('samantha');
        $this->assertTrue($status);
```

2021-12-24 03:55 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/test/Dao/EmployeeDaoTest.php
>          $this->assertEquals(false, $status);
```suggestion
        $status = $this->employeeDao->isWorkEmailAvailable('renukshan@xample.com');
        $this->assertTrue($status);
```

2021-12-24 03:55 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/test/Api/ValidationProjectActivityNameAPITest.php
> +        $this->populateFixtures('ProjectActivityAPI.yaml');
Preferred if you can use the same name of the class. e.g. `ValidationProjectActivityNameAPITest.yaml`

2021-12-24 03:55 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/test/Api/ValidationProjectActivityNameAPITest.php
> +        return $this->getTestCases('ProjectActivityNameTestCase.yaml', 'GetOne');
same here. e.g. `ValidationProjectActivityNameAPITestCases.yaml`

2021-12-24 03:55 UTC, RajithaKumara commented on symfony/plugins/orangehrmTimePlugin/test/Dao/CustomerDaoTest.php
> +        $this->assertEquals(null, $result);
```suggestion
        $this->assertNull($result);
```

2021-12-24 03:56 UTC, merged