OHRM5X-1001: Employee time sheet with pending action get all API added
orangehrm/orangehrm pull request #1083
Opened 2022-01-06 07:20 UTC by VageeshOrangeHRM

This PR Contains following changes:
1. OHRM5X-1001 - Employee Timesheets - Get Timesheets with Pending action API added.
2. Data group and role permissions added for the endpoint.
3. Unit test covered for the end point.
4. Code refactor added in some files.

2022-01-06 18:02 UTC, RajithaKumara requested changes

2022-01-06 18:02 UTC, RajithaKumara commented on installer/dbscript/dbscript-2.sql
> +       ('apiv2_time_employee_timesheet_action', 'API-v2 Time - Employee Timesheets action', 1, 0, 0, 0),
```suggestion
       ('apiv2_time_employee_timesheet_list', 'API-v2 Time - Employee Timesheet List', 1, 0, 0, 0),
```

2022-01-06 18:02 UTC, RajithaKumara commented on installer/dbscript/dbscript-2.sql
> +       ('OrangeHRM\\Time\\Api\\EmployeeTimesheetActionAPI', @time_module_id, @apiv2_time_employee_timesheet_action_data_group_id),
```suggestion
       ('OrangeHRM\\Time\\Api\\EmployeeTimesheetListAPI', @time_module_id, @apiv2_time_employee_timesheet_action_data_group_id),
```

2022-01-07 04:45 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Api/EmployeeTimesheetActionAPI.php
> +            ->getEmployeeTimesheetListByState($employeeTimesheetActionSearchParamHolder);
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Api/EmployeeTimesheetActionAPI.php
> +            ->getEmployeeTimesheetListCountByState($employeeTimesheetActionSearchParamHolder);
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Api/EmployeeTimesheetActionAPI.php
> +class EmployeeTimesheetActionAPI extends Endpoint implements CollectionEndpoint
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Dao/TimesheetDao.php
> +        $q->setParameter('states', $employeeTimesheetActionSearchFilterParams->getActionableStatesList());
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Dto/EmployeeTimesheetActionSearchFilterParams.php
> +class EmployeeTimesheetActionSearchFilterParams extends FilterParams
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/config/routes.yaml
> +  path: /api/v2/time/employees/timesheets
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/config/routes.yaml
> +    _api: OrangeHRM\Time\Api\EmployeeTimesheetActionAPI
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/test/Api/EmployeeTimesheetActionAPITest.php
> +class EmployeeTimesheetActionAPITest extends EndpointIntegrationTestCase
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/test/Api/EmployeeTimesheetActionAPITest.php
> +        return $this->getTestCases('EmployeeTimesheetActionTestCase.yaml', 'GetAll');
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/test/Api/EmployeeTimesheetActionAPITest.php
> +        $this->populateFixtures('EmployeeTimesheetActionAPI.yaml', null, true);
done

2022-01-07 04:46 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/config/routes.yaml
> +apiv2_time_employee_timesheets:
done

2022-01-07 04:47 UTC, VageeshOrangeHRM commented on installer/dbscript/dbscript-2.sql
> +       ('apiv2_time_employee_timesheet_action', 'API-v2 Time - Employee Timesheets action', 1, 0, 0, 0),
done

2022-01-07 04:47 UTC, VageeshOrangeHRM commented on installer/dbscript/dbscript-2.sql
> +       ('OrangeHRM\\Time\\Api\\EmployeeTimesheetActionAPI', @time_module_id, @apiv2_time_employee_timesheet_action_data_group_id),
done

2022-01-07 05:30 UTC, RajithaKumara approved these changes

2022-01-07 05:35 UTC, merged