OHRM5X-1106: Project Report API linked with FE
orangehrm/orangehrm pull request #1097
Opened 2022-01-19 05:29 UTC by VageeshOrangeHRM

2022-01-19 05:41 UTC, Super-Chama commented on symfony/plugins/orangehrmTimePlugin/Controller/ProjectActivityReportController.php
>              // TODO: Get project object
Remove this comment

2022-01-19 05:42 UTC, Super-Chama approved these changes
Hope you will update the employee report as well ?

2022-01-19 05:54 UTC, VageeshOrangeHRM commented on symfony/plugins/orangehrmTimePlugin/Controller/ProjectActivityReportController.php
>              // TODO: Get project object
done

2022-01-19 09:00 UTC, RajithaKumara requested changes
Can you remove mock controllers and routes

2022-01-20 04:20 UTC, RajithaKumara approved these changes

2022-01-20 04:21 UTC, merged