OHRM5X-1075: Initial Attendance plugin directory structure setup and Entity creation
orangehrm/orangehrm pull request #1100
Opened 2022-01-20 06:31 UTC by SandeepaOHRM

**This PR contains:**

- Initial Attendance plugin directory structure
- Attendance Record entity with unit testings
- bug fixes for API Issues in Employee Reports (supervisor self view employee reports is not finalised)

2022-01-20 06:35 UTC, SandeepaOHRM commented on symfony/plugins/orangehrmTimePlugin/test/fixtures/testcases/EmployeeReportDataAPITestCase.yaml
> +
This test case is commented since it is not finalised about the supervisor self view his own employee report. Can remove or uncomment once finalised.

2022-01-21 05:20 UTC, RajithaKumara requested changes

2022-01-21 05:20 UTC, RajithaKumara commented on symfony/plugins/orangehrmAttendancePlugin/entity/AttendanceRecord.php
> +    private ?DateTime $punchOutUserTime;
```suggestion
    private ?DateTime $punchOutUserTime = null;
```

2022-01-21 05:20 UTC, RajithaKumara commented on symfony/plugins/orangehrmAttendancePlugin/lib/form/ConfigureForm.php
>  <?php
No need files in `symfony/plugins/orangehrmAttendancePlugin/lib/form`

2022-01-21 05:52 UTC, RajithaKumara approved these changes

2022-01-21 05:52 UTC, RajithaKumara commented on symfony/plugins/orangehrmAttendancePlugin/entity/AttendanceRecord.php
> +     * @ORM\JoinColumn(name="employee_id", referencedColumnName="emp_number",nullable=false)
```suggestion
     * @ORM\JoinColumn(name="employee_id", referencedColumnName="emp_number", nullable=false)
```

2022-01-21 05:54 UTC, merged