OHRM5X-1105: Developed Employee Trackers List View
orangehrm/orangehrm pull request #1108
Opened 2022-01-26 06:15 UTC by ChenukaGamage

2022-01-27 04:00 UTC, Super-Chama requested changes

2022-01-27 07:10 UTC, ChenukaGamage commented on symfony/client/src/orangehrmPerformancePlugin/pages/EmployeeTrackers.vue
> +      empName: item.empName,
I removed the normaliser.

2022-01-27 07:10 UTC, ChenukaGamage commented on symfony/client/src/orangehrmPerformancePlugin/pages/EmployeeTrackers.vue
> +const userdataNormalizer = data => {
I have removed it now.

2022-01-27 07:10 UTC, ChenukaGamage commented on symfony/client/src/orangehrmPerformancePlugin/pages/EmployeeTrackers.vue
> +<style scoped></style>
Updated

2022-01-27 07:10 UTC, ChenukaGamage commented on symfony/client/src/orangehrmPerformancePlugin/pages/EmployeeTrackers.vue
> +      checkedItems: [],
Updated

2022-01-27 07:10 UTC, ChenukaGamage commented on symfony/client/src/orangehrmPerformancePlugin/pages/EmployeeTrackers.vue
> +      this.checkedItems = [];
Updated

2022-01-27 07:10 UTC, ChenukaGamage commented on symfony/client/src/orangehrmPerformancePlugin/pages/EmployeeTrackers.vue
> +          v-model:selected="checkedItems"
Updated

2022-01-27 07:10 UTC, ChenukaGamage commented on symfony/plugins/orangehrmPerformancePlugin/config/routes.yaml
> +#performance_module_under_development: # remove this
Removed

2022-01-27 07:10 UTC, ChenukaGamage commented on symfony/plugins/orangehrmPerformancePlugin/config/routes.yaml
> +performance_employee_tracker: # remove this
Removed

2022-01-28 06:13 UTC, Super-Chama approved these changes

2022-02-10 07:21 UTC, RajithaKumara approved these changes

2022-02-10 07:54 UTC, SharukaNP approved these changes

2022-02-10 11:29 UTC, merged