OHRM5X-1104: Developed My Trackers List View
orangehrm/orangehrm pull request #1109
Opened 2022-01-26 06:15 UTC by AnikaSaparamadu

2022-01-26 08:10 UTC, samanthajayasinghe commented on symfony/plugins/orangehrmPerformancePlugin/config/routes.yaml
> +  methods: [ GET ]
pls add a new line to the end of the file ..

2022-01-27 04:05 UTC, Super-Chama requested changes

2022-01-27 04:05 UTC, Super-Chama commented on symfony/client/src/pages.ts
> +import Todo from '@/orangehrmPerformancePlugin/pages/Todo.vue';
Please remove todo screen. (it was only for training)

2022-01-27 04:05 UTC, Super-Chama commented on symfony/plugins/orangehrmPerformancePlugin/config/routes.yaml
> +#  path: /performance/{screen}
Need to remove commented code.

2022-01-27 04:05 UTC, Super-Chama commented on symfony/plugins/orangehrmPerformancePlugin/config/routes.yaml
> +performance_todo: # remove this
remove `# remove this` comment

2022-01-27 04:05 UTC, Super-Chama commented on symfony/client/src/orangehrmPerformancePlugin/pages/MyTracker.vue
> +        :selected="checkedItems.length"
let's remove checkedItems and set 0

2022-01-27 04:05 UTC, Super-Chama commented on symfony/client/src/orangehrmPerformancePlugin/pages/MyTracker.vue
> +          v-model:selected="checkedItems"
remove v-model:selected="checkedItems"

2022-01-27 04:05 UTC, Super-Chama commented on symfony/client/src/orangehrmPerformancePlugin/pages/MyTracker.vue
> +      checkedItems: [],
can remove `checkedItems` since there is no select option in table

2022-01-27 04:05 UTC, Super-Chama commented on symfony/client/src/orangehrmPerformancePlugin/pages/MyTracker.vue
> +<style scoped></style>
remove empty tag

2022-01-28 09:10 UTC, Super-Chama commented on symfony/plugins/orangehrmPerformancePlugin/config/routes.yaml
> +performance_myTrackers: # remove this
please remove `# remove this` comment

2022-01-28 09:10 UTC, Super-Chama approved these changes

2022-02-09 15:26 UTC, merged