OHRM5X-1080: Time - Punch in/out screen connect BE
orangehrm/orangehrm pull request #1126
Opened 2022-02-17 06:24 UTC by Super-Chama

2022-02-17 06:58 UTC, SharukaNP reviewed
All good

2022-02-17 07:51 UTC, SandeepaOHRM approved these changes

2022-02-21 04:18 UTC, RajithaKumara requested changes
- Seems current time automatically updates when the user able to edit time
- Need to show punch In time and note in punch out screen

2022-02-21 07:32 UTC, RajithaKumara approved these changes

2022-02-21 07:34 UTC, merged