OHRM5X-1205: Access employee lang string
orangehrm/orangehrm pull request #1187
Opened 2022-03-21 03:33 UTC by Ajiharan007

2022-03-21 08:00 UTC, RajithaKumara commented on symfony/client/src/orangehrmPimPlugin/components/FullNameInput.vue
> +        placeholder: 'Middle Name',
have to check i18n support

2022-03-22 11:14 UTC, RajithaKumara commented
Have to cherry-pick from [here](https://github.com/orangehrm/orangehrm/pull/976/commits/0e3f3c8a6b7509c621f4a2a5e4d3da47a1fcd8e6)
```bash
git fetch upstream
git checkout -b OHRM5X-1205--Access-employee-lang-string upstream/5.0-i18n
git cherry-pick 3a1392c^..3771962
# resolve conflicts
```

2022-03-23 04:14 UTC, Ajiharan007 commented on symfony/client/src/orangehrmPimPlugin/components/FullNameInput.vue
> -        placeholder: "$t('middle_name')",
cannot use this keyword in default value

2022-03-23 05:18 UTC, RajithaKumara requested changes
Shall we do it like this?

2022-03-23 05:18 UTC, RajithaKumara commented on symfony/client/src/orangehrmPimPlugin/components/FullNameInput.vue
>      },
shall we go like this then,
```js
showMiddleNamePlaceholder: {
      type: Boolean,
      default: true,
}

2022-03-23 05:18 UTC, RajithaKumara commented on symfony/client/src/orangehrmPimPlugin/components/FullNameInput.vue
> +      :placeholder="middleNameProps ? middleName : $t('general.middle_name')"
```suggestion
      :placeholder="showMiddleNamePlaceholder ? $t('general.middle_name') : ''"
```

2022-03-23 05:18 UTC, RajithaKumara commented on symfony/client/src/orangehrmMaintenancePlugin/components/SelectedEmployee.vue
> +                  middle-name-props
```suggestion
                  :show-middle-name-placeholder="false"
```

2022-03-23 11:45 UTC, merged