Attendance
orangehrm/orangehrm pull request #1188
Opened 2022-03-21 04:20 UTC by SharukaNP

2022-03-21 13:17 UTC, RajithaKumara requested changes

2022-03-21 13:17 UTC, RajithaKumara commented on symfony/client/src/orangehrmAdminPlugin/pages/emailConfiguration/ViewEmailConfiguration.vue
> +                    'admin.optional_the_mail_server_requires_the_use_of_tls_security',
:ok_hand:

2022-03-22 04:06 UTC, SharukaNP commented on installer/upgrader/Migrations/V5/generalLangString.yaml
> +    unitId: test
removed

2022-03-22 04:08 UTC, SharukaNP commented on installer/upgrader/Migrations/V5/generalLangString.yaml
> +    value: 'yyyy-mm-dd'
when we start date format localization we could set to change this one string and it should change everywhere.

2022-03-22 04:09 UTC, SharukaNP commented on installer/upgrader/Migrations/V5/generalLangString.yaml
> +    value: 'Accepts upto 1 mb'
Didn't we discuss to keep this as a static and if any customization in validation to customize the string?

2022-03-22 04:10 UTC, SharukaNP commented on installer/upgrader/Migrations/V5/helpLangString.yaml
> +    unitId: we_will_be_delighted_to_help
I thought on that but here right now the email is hard coded on to the page so sending as a parameter would be redundant right?

2022-03-22 04:12 UTC, SharukaNP commented on symfony/client/src/orangehrmAdminPlugin/pages/emailConfiguration/ViewEmailConfiguration.vue
> +          <oxd-button display-type="ghost" :label="Reset" @click="onReset" />
Changed

2022-03-22 04:13 UTC, SharukaNP commented on symfony/client/src/orangehrmAttendancePlugin/components/RecordAttendance.vue
> +            :placeholder="$t('general.date_format')"
I'll  explain during the meeting today on the process I thought for this

2022-03-25 14:24 UTC, SharukaNP commented on installer/upgrader/Migrations/V5/generalLangString.yaml
> +    value: 'This page is being developed for the OrangeHRM OS 5.0 Beta version.'
Chnaged Based on Kavinda's recomendation.

2022-03-25 15:45 UTC, SharukaNP commented on installer/upgrader/Migrations/V5/helpLangString.yaml
> +    unitId: we_will_be_delighted_to_help
Ok so I did a bit of research on this [https://docs.google.com/document/d/1qcd-jykSQnjTsuLd8T--NyFjT2zMXncS55TTPwrxA5Y/edit#](url)

2022-03-27 03:24 UTC, RajithaKumara requested changes

2022-03-27 03:24 UTC, RajithaKumara commented on installer/dbscript/dbscript-2.sql
> +INSERT INTO `ohrm_i18n_group` (`name`, `title`) VALUES ('attendance', 'Attendance'), ('help', 'Help'),('authentication', 'Authentication');
```suggestion
INSERT INTO `ohrm_i18n_group` (`name`, `title`) VALUES ('attendance', 'Attendance'), ('help', 'Help'),('auth', 'Authentication');
```
Shall we go as `auth` cz it short

2022-03-27 15:32 UTC, SharukaNP commented on installer/dbscript/dbscript-2.sql
> +INSERT INTO `ohrm_i18n_group` (`name`, `title`) VALUES ('attendance', 'Attendance'), ('help', 'Help'),('authentication', 'Authentication');
changed authentication group to auth

2022-03-28 05:46 UTC, RajithaKumara commented on symfony/client/src/core/pages/ModuleUnderDevelopment.vue
>              href="https://sourceforge.net/projects/orangehrm/files/stable/4.9/"
check this also

2022-03-28 11:50 UTC, SharukaNP commented on symfony/client/src/core/pages/ModuleUnderDevelopment.vue
>              href="https://sourceforge.net/projects/orangehrm/files/stable/4.9/"
added link

2022-03-28 12:13 UTC, SharukaNP commented on installer/upgrader/Migrations/V5/TranslationTool.php
> +        //$filename = 'installer/upgrader/Migrations/V5/messages.bg_BG.xml';
Has been removed in the next commit

2022-03-28 13:15 UTC, RajithaKumara approved these changes

2022-03-28 13:21 UTC, merged