OHRM5X-1202 : Fix translation bugs for QA exceptance
orangehrm/orangehrm pull request #1205
Opened 2022-03-31 04:22 UTC by SharukaNP

2022-03-31 06:44 UTC, SharukaNP reviewed
Removed the exception translation which cause errors

2022-04-01 04:38 UTC, RajithaKumara requested changes
Format all modified files using IDE

2022-04-01 04:38 UTC, RajithaKumara commented on symfony/plugins/orangehrmLeavePlugin/Controller/LeaveListController.php
> +                'label' =>$this->getI18NHelper()->transBySource($leaveStatus['label']),
```suggestion
                'label' => $this->getI18NHelper()->transBySource($leaveStatus['label']),
```
format the code

2022-04-01 04:38 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Controller/SaveCustomFieldController.php
> +    use I18NHelperTrait;
```suggestion
    use I18NHelperTrait;

```
add new line

2022-04-01 04:38 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Controller/SaveCustomFieldController.php
> +        $component->addProp(new Prop('field-type-list', Prop::TYPE_ARRAY, $translatedFieldTypeList));
shall we go like this,
```php
        $component->addProp(
            new Prop(
                'screen-list',
                Prop::TYPE_ARRAY,
                array_map(
                    fn (array $screen) => [
                        'id' => $screen['id'],
                        'label' => $this->getI18NHelper()->transBySource($screen['label'])
                    ],
                    CustomFieldController::SCREEN_LIST
                )
            )
        );
        $component->addProp(
            new Prop(
                'field-type-list',
                Prop::TYPE_ARRAY,
                array_map(
                    fn (array $screen) => [
                        'id' => $screen['id'],
                        'label' => $this->getI18NHelper()->transBySource($screen['label'])
                    ],
                    CustomFieldController::FIELD_TYPE_LIST
                )
            )
        );
```

2022-04-04 03:13 UTC, devishke-orange commented on symfony/plugins/orangehrmPimPlugin/Controller/SaveEmployeeReportController.php
> +    private function translateFields(array $fields): array
add php doc comment

2022-04-07 07:18 UTC, Super-Chama approved these changes

2022-04-07 08:35 UTC, RajithaKumara approved these changes

2022-04-07 08:35 UTC, RajithaKumara commented on installer/dbscript/dbscript-2.sql
> +ALTER TABLE `ohrm_module` ADD display_name VARCHAR(120);
please note this, need to move to migration file

2022-04-07 08:42 UTC, merged