OHRM5X-1263:  employee list navigation issue
orangehrm/orangehrm pull request #1237
Opened 2022-04-19 10:06 UTC by Ajiharan007

2022-04-21 06:14 UTC, Super-Chama requested changes

2022-04-21 06:14 UTC, Super-Chama commented on src/client/src/orangehrmPimPlugin/pages/employee/Employee.vue
> +          :clickable="false"
This will disable the clicking on row. we need to be able to click the row and navigate to profile

2022-04-21 07:40 UTC, Super-Chama commented on src/client/src/orangehrmPimPlugin/pages/employee/Employee.vue
> +          :clickable="false"
@Ajiharan007 Please check this with 50-beta and let me know what change have caused this. the fix probably should apply from OXD Library side

2022-04-21 13:28 UTC, Super-Chama approved these changes
This does not fix navigation issue, but other fixes are approved

2022-04-25 17:20 UTC, RajithaKumara approved these changes

2022-04-25 17:23 UTC, merged