OHRM5X-781: Installer - missing installation steps
orangehrm/orangehrm pull request #1255
Opened 2022-04-26 03:55 UTC by Super-Chama

… screen redirect fixes

2022-04-26 16:29 UTC, devishke-orange requested changes
few suggestion here and there. Also tried installing via a build but couldn't get system check screen to work. Not sure what the issue is.

Always getting this error regardless of DB
![image](https://user-images.githubusercontent.com/97493184/165348320-f6cecd13-ac05-4d04-9695-5d549ee5a26a.png)

2022-04-26 16:29 UTC, devishke-orange commented on installer/client/src/components/GNULicence.vue
> +Copyright (C) 1989, 1991 Free Software Foundation, Inc.
can't we use `&copy;` to get copyright symbol?
```suggestion
Copyright &copy; 1989, 1991 Free Software Foundation, Inc.  
```

![image](https://user-images.githubusercontent.com/97493184/165347681-140de6f0-d8ee-46a6-b5ea-0f6752a5451c.png)

2022-04-26 19:22 UTC, Super-Chama commented on installer/client/src/pages/InstanceCreationScreen.vue
> +    this.isLoading = false;
yes, updated

2022-04-26 19:22 UTC, Super-Chama commented on installer/client/src/pages/UpgraderCompleteScreen.vue
> +      start using the system.
went with #2 for now

2022-04-27 02:27 UTC, RajithaKumara approved these changes

2022-04-27 06:10 UTC, SharukaNP commented
> few suggestion here and there. Also tried installing via a build but couldn't get system check screen to work. Not sure what the issue is.
> 
> Always getting this error regardless of DB ![image](https://user-images.githubusercontent.com/97493184/165348320-f6cecd13-ac05-4d04-9695-5d549ee5a26a.png)

I got the same error today

2022-04-27 06:11 UTC, Super-Chama commented on installer/client/src/pages/LicenceAcceptanceScreen.vue
> +  // },
removed

2022-04-27 06:15 UTC, SandeepaOHRM commented
This database engine issue is fixed and the fix is with this PR

2022-04-27 06:19 UTC, SandeepaOHRM commented on installer/Util/SystemConfig.php
> +            $engines = $connection->query("SHOW ENGINES")->fetchAll(PDO::FETCH_ASSOC);
Database engine check - InnoDB failing issue fixed with PDO Connection

2022-04-27 06:19 UTC, SharukaNP commented
![InstallerBuildTest1](https://user-images.githubusercontent.com/97490773/165453841-b7550849-b425-4c9d-87ac-564310043387.png)

DO we need this warning for fresh install?

2022-04-27 06:21 UTC, SharukaNP commented
> > few suggestion here and there. Also tried installing via a build but couldn't get system check screen to work. Not sure what the issue is.
> > Always getting this error regardless of DB ![image](https://user-images.githubusercontent.com/97493184/165348320-f6cecd13-ac05-4d04-9695-5d549ee5a26a.png)
> 
> I got the same error today but only in main branch I'll test this too

No longer there in the build so this error is fixed.

2022-04-27 06:27 UTC, SharukaNP commented
Build is working can install properly (tested on mariadb 104)

2022-04-27 06:59 UTC, Super-Chama commented
> ![InstallerBuildTest1](https://user-images.githubusercontent.com/97490773/165453841-b7550849-b425-4c9d-87ac-564310043387.png)
> 
> DO we need this warning for fresh install?

Fixed in #1253

2022-04-27 11:36 UTC, RajithaKumara approved these changes

2022-04-27 11:36 UTC, RajithaKumara commented on installer/client/src/pages/LicenceAcceptanceScreen.vue
> +import GNULicence from '@/components/GNULicence.vue';
*

2022-04-27 11:39 UTC, Super-Chama commented on installer/client/src/pages/LicenceAcceptanceScreen.vue
> +import GNULicence from '@/components/GNULicence.vue';
Component name?

2022-04-27 12:30 UTC, RajithaKumara commented on installer/client/src/pages/LicenceAcceptanceScreen.vue
> +import GNULicence from '@/components/GNULicence.vue';
just marked it. will double check it

2022-04-27 16:58 UTC, RajithaKumara approved these changes

2022-04-27 17:10 UTC, merged