OHRM5X-1103 : Configure Performance Trackers
orangehrm/orangehrm pull request #1279
Opened 2022-05-05 02:22 UTC by SharukaNP

2022-05-05 08:54 UTC, Super-Chama requested changes

2022-05-05 08:54 UTC, Super-Chama commented on src/client/src/orangehrmPerformancePlugin/components/ReviewersAutoComplete.vue
> +<style scoped>
if past emp tag not used, remove this style

2022-05-05 08:54 UTC, Super-Chama commented on src/client/src/orangehrmPerformancePlugin/pages/PerformanceTrackers.vue
> +          ${row.employee?.terminationId ? ' (Past Employee)' : ''}`,
Past employee translation

2022-05-06 09:27 UTC, SharukaNP commented on src/client/src/orangehrmPerformancePlugin/pages/PerformanceTrackers.vue
> +          ${row.employee?.terminationId ? ' (Past Employee)' : ''}`,
Added

2022-05-11 11:29 UTC, SharukaNP commented
This PR is closed since the commits in this are included in a new PR as the commits are interrelated

2022-05-11 11:29 UTC, closed without merging