OHRM5X-1359: Candidate Workflow
orangehrm/orangehrm pull request #1303
Opened 2022-05-27 08:54 UTC by SandeepaOHRM

This PR contains:-

  Entities:-
  - CandidateHistory
  - Interview
  - InterviewAttachment
  
API to get allowed candidate actions

2022-05-27 12:49 UTC, RajithaKumara requested changes

2022-05-27 12:49 UTC, RajithaKumara commented on src/plugins/orangehrmRecruitmentPlugin/entity/Decorator/CandidateHistoryDecorator.php
> +    public function setInterview(int $id): void
doc comment

2022-05-27 12:49 UTC, RajithaKumara commented on src/plugins/orangehrmRecruitmentPlugin/entity/Decorator/InterviewAttachmentDecorator.php
> +    public function getInterviewAttachment(): InterviewAttachment
```suggestion
    protected function getInterviewAttachment(): InterviewAttachment
```

2022-05-27 12:49 UTC, RajithaKumara commented on src/plugins/orangehrmRecruitmentPlugin/entity/Interview.php
> + * @method InterviewDecorator getDecorator()
```suggestion
 * @method InterviewDecorator getDecorator()
 *
```

2022-05-30 05:11 UTC, SandeepaOHRM commented on src/plugins/orangehrmRecruitmentPlugin/entity/Decorator/CandidateHistoryDecorator.php
> +    public function setInterview(int $id): void
done

2022-05-30 05:11 UTC, SandeepaOHRM commented on src/plugins/orangehrmRecruitmentPlugin/entity/Decorator/InterviewAttachmentDecorator.php
> +    public function getInterviewAttachment(): InterviewAttachment
done

2022-05-30 05:11 UTC, SandeepaOHRM commented on src/plugins/orangehrmRecruitmentPlugin/entity/Interview.php
> + * @method InterviewDecorator getDecorator()
done

2022-05-30 10:15 UTC, RajithaKumara approved these changes

2022-05-30 10:15 UTC, RajithaKumara commented on src/plugins/orangehrmRecruitmentPlugin/entity/CandidateHistory.php
> +    private ?string $interviewers = null;
is this correct?

2022-05-30 10:20 UTC, merged