OHRM5X-1452 : Supervisor Evaluation API
orangehrm/orangehrm pull request #1324
Opened 2022-06-10 02:30 UTC by SharukaNP

2022-06-13 04:32 UTC, RajithaKumara requested changes

2022-06-13 04:32 UTC, RajithaKumara commented on installer/Migration/V5_1_0/permission/api.yaml
> +    create: true
```suggestion
    create: false
```

2022-06-13 04:32 UTC, RajithaKumara commented on installer/Migration/V5_1_0/permission/api.yaml
> +    - { role: ESS, permission: { read: true,  create: true, update: true, delete: false } }
this rule seems wrong

2022-06-13 04:32 UTC, RajithaKumara commented on src/plugins/orangehrmPerformancePlugin/Api/Model/ReviewerRatingModel.php
> +                'kpiId',
```suggestion
                ['kpi', 'id'],
```
shall we go like this? in case we can add `title` also

2022-06-13 04:32 UTC, RajithaKumara commented on src/plugins/orangehrmPerformancePlugin/Api/SupervisorEvaluationAPI.php
> +                throw $this->getBadRequestException('Performed action not allowed');
```suggestion
                throw $this->getForbiddenException();
```

2022-06-15 09:35 UTC, SandeepaOHRM requested changes

2022-06-15 09:35 UTC, SandeepaOHRM commented on src/plugins/orangehrmPerformancePlugin/Api/ValidationRules/ReviewReviewerRatingParamRule.php
> +            ->getKpiIdsForReviewId($this->reviewId);*/
Commented code?

2022-06-15 09:35 UTC, SandeepaOHRM commented on src/plugins/orangehrmPerformancePlugin/Api/ValidationRules/ReviewReviewerRatingParamRule.php
> +            }
```suggestion
            if (count(array_keys($rating)) != 3 || !(isset($rating[SupervisorEvaluationAPI::PARAMETER_KPI_ID]))) {
                return false;
            }
```
Shall we remove repetitive if blocks like this way?

2022-06-15 09:35 UTC, SandeepaOHRM commented on src/plugins/orangehrmPerformancePlugin/Api/ValidationRules/ReviewReviewerRatingParamRule.php
> +            if (count(array_keys($rating)) != 3) {
Use defined constant instead of 3 if possible

2022-06-15 09:35 UTC, SandeepaOHRM commented on src/plugins/orangehrmPerformancePlugin/Dao/PerformanceReviewDao.php
> +    public function generateReviewReviewerRatingKey(int $reviewerId, int $performanceReviewId, int $kpiId): string
Doesn't know about the context, but this method seems not interacting with the ORM, is it possible to move this to service layer instead?

2022-06-15 09:35 UTC, SandeepaOHRM commented on src/plugins/orangehrmPerformancePlugin/Api/ValidationRules/ReviewReviewerRatingParamRule.php
> +            }
```suggestion
            if (!(is_numeric($kpiId) && ($kpiId > 0)) || !in_array($kpiId, array_column($kpisForReview, 'id'))) {
                return false;
            }
```

2022-06-16 09:53 UTC, SharukaNP commented
![PerformanceStates-Self Review](https://user-images.githubusercontent.com/97490773/174044718-08c9e9bc-01b4-47db-bb89-b8304cfaf63d.jpg)

2022-06-16 10:09 UTC, RajithaKumara approved these changes

2022-06-16 10:18 UTC, merged