OHRM5X-1477: Test Automation : Leave - Leave period
orangehrm/orangehrm pull request #1325
Opened 2022-06-10 08:43 UTC by OvaraPerera

2022-06-16 10:29 UTC, RajithaKumara requested changes

2022-06-16 10:29 UTC, RajithaKumara commented on src/test/functional/cypress/integration/feature/Leave/leavePeriod.spec.js
> +      //cy.toast('success', 'Successfully Saved');
no commented codes. is this pending assertion

2022-06-16 10:29 UTC, RajithaKumara commented on src/test/functional/cypress/integration/feature/Leave/leavePeriod.spec.js
> +      //cy.toast('success', 'Successfully Saved');
no commented codes

2022-06-16 10:29 UTC, RajithaKumara commented on src/test/functional/cypress/integration/feature/Leave/leavePeriod.spec.js
> +      //cy.toast('success', 'Successfully Saved');
no commented codes

2022-06-17 09:40 UTC, OvaraPerera commented
Closed as a new PR was added.
New PR Link- https://github.com/orangehrm/orangehrm/pull/1338

2022-06-17 09:40 UTC, closed without merging