OHRM5X-1196 Update to translate language as bulk
orangehrm/orangehrm pull request #1368
Opened 2022-07-07 03:18 UTC by ManulMax

2022-07-07 06:36 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationAPI.php
> +    use EntityManagerHelperTrait;
Remove

2022-07-07 06:36 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationBulkAPI.php
> +                            ),
** need to handle lang string ID

2022-07-07 06:36 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationBulkAPI.php
> +            array_values($translatedDataValues),
*

2022-07-07 06:36 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/config/routes.yaml
> +  requirements:
remove

2022-07-07 06:36 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/test/Api/I18NTranslationBulkAPITest.php
> +namespace Api;
change

2022-07-07 06:36 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/test/Api/I18NTranslationBulkAPITest.php
> +        $this->createKernelWithMockServices([Services::DATETIME_HELPER_SERVICE => new DateTimeHelperService()]);
```suggestion
```

2022-07-07 09:43 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationAPI.php
> +    use EntityManagerHelperTrait;
Removed

2022-07-07 09:44 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationBulkAPI.php
> +                            ),
Add langStringId

2022-07-07 09:44 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/config/routes.yaml
> +  requirements:
removed

2022-07-07 09:44 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/test/Api/I18NTranslationBulkAPITest.php
> +namespace Api;
changed namespace

2022-07-07 09:44 UTC, ManulMax commented on src/plugins/orangehrmAdminPlugin/test/Api/I18NTranslationBulkAPITest.php
> +        $this->createKernelWithMockServices([Services::DATETIME_HELPER_SERVICE => new DateTimeHelperService()]);
removed

2022-07-08 04:18 UTC, RajithaKumara requested changes

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Service/LocalizationService.php
> +     * @param array $rows
```suggestion
     * @param array $rows e.g. [['langStringId'=> 1, 'translatedValue' => 'Employee'], ['langStringId'=> 2, 'translatedValue' => 'Admin']]
```
add an example like this

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Service/LocalizationService.php
> +    public function saveAndUpdateTranslatedStringsFromRows(int $languageId, array $rows)
```suggestion
    public function saveAndUpdateTranslatedStringsFromRows(int $languageId, array $rows): void
```

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Service/LocalizationService.php
> +     * @return array
```suggestion
     * @return I18NTranslation[]
```

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Service/LocalizationService.php
> +                throw new LogicException('langStringId is required attribute');
```suggestion
                throw new \LogicException('langStringId is required attribute');
```
when you are using classes namespace should consider. you have used it from `SebastianBergmann\Type\LogicException` it's wrong

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/test/fixtures/testcases/I18NTranslationBulkAPITestCases.yaml
> +      message: 'Invalid Parameter'
I think need to handle some more routes

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationBulkAPI.php
> +            throw $e;
```suggestion
```

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationBulkAPI.php
> +                ->saveAndUpdateTranslatedStringsFromRows($languageId, $translatedDataValues);
```suggestion
            $this->getLocalizationService()
                ->saveAndUpdateTranslatedStringsFromRows($languageId, $translatedDataValues);
            $this->commitTransaction();
```
commit the transaction within try block

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationBulkAPI.php
> +        $this->commitTransaction();
```suggestion
```

2022-07-08 04:18 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Api/I18NTranslationBulkAPI.php
> +            array_values($translatedDataValues),
this we may have to remove.

2022-07-14 03:20 UTC, RajithaKumara requested changes

2022-07-14 03:20 UTC, RajithaKumara commented on src/plugins/orangehrmI18NPlugin/entity/Decorator/I18NTranslationDecorator.php
> +    public function getI18NTranslation(): I18NTranslation
```suggestion
    protected function getI18NTranslation(): I18NTranslation
```

2022-07-14 03:20 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/test/fixtures/testcases/I18NTranslationBulkAPITestCases.yaml
> +    data: []
since data is empty, don't have way to check translated strings actually saved

2022-07-14 03:20 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/test/Api/I18NTranslationBulkAPITest.php
> +        $this->populateFixtures('I18NTranslationAPI.yml');
create a new fixture file for this test. don't reuse `I18NTranslationAPI.yml`

2022-07-14 03:24 UTC, merged