Ohrm5 x 824
orangehrm/orangehrm pull request #1402
Opened 2022-07-27 08:28 UTC by SharukaNP

2022-07-27 08:34 UTC, SharukaNP commented on src/lib/framework/Services.php
> +
Remove empty line

2022-07-27 08:34 UTC, SharukaNP commented on src/plugins/orangehrmPimPlugin/Api/PimReportDataAPI.php
> +
remove empty line

2022-07-27 08:34 UTC, SharukaNP commented on src/plugins/orangehrmPimPlugin/Dao/CustomFieldDao.php
>          if (!(strlen((string)$seqNo) <= 10 && $seqNo > 0)) {
update doc comment for transaction

2022-07-27 08:34 UTC, SharukaNP commented on src/plugins/orangehrmPimPlugin/Dao/CustomFieldDao.php
doc comment

2022-07-28 03:58 UTC, RajithaKumara requested changes

2022-08-09 08:43 UTC, SharukaNP commented on src/plugins/orangehrmCorePlugin/Dao/ReportGeneratorDao.php
> +        $q->select('displayFieldGroup.id,displayFieldGroup.name');
Change to object array

2022-08-17 03:53 UTC, RajithaKumara requested changes

2022-08-17 03:53 UTC, RajithaKumara commented on src/plugins/orangehrmAdminPlugin/Api/EmailConfigurationAPI.php
> +        $emailConfiguration->setSmtpPassword($password);
Want to discuss this.

2022-08-17 03:53 UTC, RajithaKumara commented on src/plugins/orangehrmCorePlugin/test/Dao/ReportGeneratorDaoTest.php
> +namespace Dao;
```suggestion
namespace OrangeHRM\Tests\Core\Dao;
```

2022-08-17 03:53 UTC, RajithaKumara commented on src/plugins/orangehrmCorePlugin/test/Dao/ReportGeneratorDaoTest.php
> +class ReportGeneratorDaoTest extends KernelTestCase
add groups annotations

2022-08-17 03:53 UTC, RajithaKumara commented on src/plugins/orangehrmPimPlugin/Dao/CustomFieldDao.php
> +    public function addCustomFieldToDisplayField(CustomField $customField): void
```suggestion
    private function addCustomFieldToDisplayField(CustomField $customField): void
```

2022-08-17 03:53 UTC, RajithaKumara commented on src/plugins/orangehrmPimPlugin/Dao/CustomFieldDao.php
> +    public function deleteDisplayFieldsOfCustomFields(array $toDeleteCustomFieldIds): void
```suggestion
    private function deleteDisplayFieldsOfCustomFields(array $toDeleteCustomFieldIds): void
```

2022-08-17 03:53 UTC, RajithaKumara commented on src/plugins/orangehrmPimPlugin/Dao/CustomFieldDao.php
>          }
```php
        if (empty($toDeleteCustomFieldIds)) {
            return;
        }
        $displayFieldNames = [];
        foreach ($toDeleteCustomFieldIds as $toDeleteCustomFieldId) {
            $customField = $this->getCustomFieldById($toDeleteCustomFieldId);
            $displayFieldNames[] = 'hs_hr_employee.custom' . $customField->getFieldNum();
        }
        $q = $this->createQueryBuilder(DisplayField::class, 'displayField');
        $q->delete()
            ->andWhere($q->expr()->in('displayField.name', ':displayFieldNames'))
            ->setParameter('displayFieldNames', $displayFieldNames);
        $q->getQuery()->execute();
```

2022-08-18 03:09 UTC, RajithaKumara approved these changes

2022-08-18 03:29 UTC, merged