OHRM5X-1661: Develop LDAP Config API
orangehrm/orangehrm pull request #1415
Opened 2022-08-18 03:25 UTC by SandeepaOHRM

2022-08-18 16:04 UTC, RajithaKumara requested changes

2022-08-18 16:04 UTC, RajithaKumara commented on src/plugins/orangehrmLDAPAuthenticationPlugin/Api/LDAPConfigAPI.php
> +        $LDAPSettings = new LDAPSetting(
```suggestion
        $ldapSettings = new LDAPSetting(
```
this also fine

2022-08-18 16:04 UTC, RajithaKumara commented on src/plugins/orangehrmLDAPAuthenticationPlugin/Dto/LDAPSetting.php
> +    public function getEncodedAttributes(): string
not sure why we need this.
can't we use `__toString`

2022-08-19 03:02 UTC, merged

2022-08-19 07:00 UTC, SandeepaOHRM commented on src/plugins/orangehrmLDAPAuthenticationPlugin/Api/LDAPConfigAPI.php
> +        $LDAPSettings = new LDAPSetting(
done

2022-08-19 07:00 UTC, SandeepaOHRM commented on src/plugins/orangehrmLDAPAuthenticationPlugin/Api/LDAPConfigAPI.php
> +    public function create(): EndpointResult
done

2022-08-19 07:01 UTC, SandeepaOHRM commented on installer/Migration/V5_2_0/permission/api.yaml
> +    - { role: Admin, permission: { read: false, create: true, update: false, delete: false } }
done

2022-08-19 07:01 UTC, SandeepaOHRM commented on installer/Migration/V5_2_0/permission/api.yaml
> +    delete: false
done

2022-08-19 07:01 UTC, SandeepaOHRM commented on installer/Migration/V5_2_0/permission/api.yaml
> +  description: 'API-v2 Admin   - LDAP Configurations'
done