OHRM5X-1655 API to get list of employees on leave
orangehrm/orangehrm pull request #1417
Opened 2022-08-18 09:23 UTC by ManulMax

2022-08-22 03:49 UTC, RajithaKumara requested changes

2022-08-22 03:49 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Dao/LeaveListDao.php
> +        ->setParameter('approved', Leave::LEAVE_STATUS_LEAVE_APPROVED);
`Leave::LEAVE_STATUS_LEAVE_TAKEN` also needs to consider right. I saw in spec

2022-08-22 03:49 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Service/LeaveListService.php
> +    private ?LeaveListDao $leaveListDao = null;
```suggestion
    /**
     * @var LeaveListDao
     */
    private LeaveListDao $leaveListDao;
```
:bulb:

2022-08-22 03:49 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Service/LeaveListService.php
> +        return $this->leaveListDao;
```suggestion
        return $this->leaveListDao ??= new LeaveListDao();
```
:bulb: 
E.g.
https://github.com/orangehrm/orangehrm/blob/5.2-ldap/src/plugins/orangehrmLDAPAuthenticationPlugin/Auth/LDAPAuthProvider.php#L28-L36

2022-08-22 03:49 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Service/Model/LeaveListModal.php
> +            ['employee','employeeId'],
:ok_hand:

2022-08-22 03:49 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Service/Model/LeaveListModal.php
> +            ['getEmployee','getEmployeeId'],
one field missing. termination id. this used to show whether the employee is past employee.
if this param null means active employee. if this param has value then we are showing `(Past Employee)` suffix

2022-08-22 03:49 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/config/routes.yaml
> +  path: /api/v2/leave/leaves/list
will discuss and move to dashboard plugin

2022-08-22 03:49 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/test/Dao/LeaveListDaoTest.php
> +namespace Dao;
```suggestion
namespace OrangeHRM\Tests\Leave\Dao;
```

2022-08-22 03:50 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Service/Model/LeaveListModal.php
> +        if ($this->getAuthUser()->getUserRoleName() === 'Admin') {
TODO:: will change this to evaluate using datagroup permission

2022-08-24 04:14 UTC, RajithaKumara requested changes

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeOnLeaveAPI.php
> +        $leaveListSearchFilterParams = new LeaveListSearchFilterParams();
```suggestion
        $employeeOnLeaveSearchFilterParams = new EmployeeOnLeaveSearchFilterParams();
```
:thinking:  can refactor rename

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeOnLeaveAPI.php
> +        );
```suggestion
        $startDate = $this->getRequestParams()->getDateTime(
            RequestParams::PARAM_TYPE_QUERY,
            self::DATE,
            null,
            $this->getDateTimeHelper()->getNow()
        );
```
define default date.

`use DateTimeHelperTrait;` use this trait

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeOnLeaveAPI.php
> +        $leaveListSearchFilterParams->setDate($startDate);
```suggestion
        $leaveListSearchFilterParams->setDate($date);
```
refactor rename

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeOnLeaveAPI.php
> +                new Rule(Rules::DATE)
```suggestion
                new Rule(Rules::API_DATE)
```

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Api/Model/EmployeeOnLeaveModal.php
> +    use ConfigServiceTrait;
```suggestion
```

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Api/Model/EmployeeOnLeaveModal.php
> +        if ($this->getUserRoleManager()->getUser()->getUserRole()->getName() === 'Admin') {
```suggestion
        if ($this->getAuthUser()->getUserRoleName() === 'Admin') {
```
can you try this now

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Dao/EmployeeOnLeaveDao.php
> +use Doctrine\ORM\Tools\Pagination\Paginator;
```suggestion
use OrangeHRM\ORM\Paginator;
```
careful about namespaces

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Dao/EmployeeOnLeaveDao.php
> +    public function getLeaveListPaginator(LeaveListSearchFilterParams $leaveListSearchFilterParams): Paginator
```suggestion
    private function getLeaveListPaginator(LeaveListSearchFilterParams $leaveListSearchFilterParams): Paginator
```

2022-08-24 04:14 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/test/Api/EmployeeOnLeaveApiTest.php
> +namespace OrangeHRM\Dashboard\test\Api;
```suggestion
namespace OrangeHRM\Tests\Dashboard\Api;
```

2022-08-24 06:29 UTC, ManulMax commented on src/plugins/orangehrmDashboardPlugin/Api/Model/EmployeeOnLeaveModal.php
> +        if ($this->getUserRoleManager()->getUser()->getUserRole()->getName() === 'Admin') {
working

2022-08-25 06:54 UTC, RajithaKumara approved these changes

2022-08-25 06:54 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Api/Model/EmployeeOnLeaveModal.php
> +            $attributeNames[] = ['leaveType', 'name'];
Oops leave type deleted attribute forgot. https://github.com/orangehrm/orangehrm/blob/main/src/plugins/orangehrmLeavePlugin/Api/Model/LeaveTypeModel.php#L40

2022-08-25 06:54 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/test/fixtures/testcases/EmployeeOnLeaveAPITestCases.yaml
> +GetAll:
seems not added tests for `limit`, `offset`, `sortOrder`, `sortField`

2022-08-26 11:28 UTC, merged