OHRM5X-1650: Dashboard Widget Common Card Component
orangehrm/orangehrm pull request #1422
Opened 2022-08-25 03:17 UTC by ManulMax

2022-08-25 03:52 UTC, Super-Chama requested changes

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/ActionButton.vue
> +<style lang=""></style>
```suggestion
```

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/ActionButton.vue
> +    <oxd-icon name="gear-fill" @click="$emit('show-actions', true)"></oxd-icon>
What if we remove outer div and pass the icon name as prop?

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/CardComponent.vue
> +        <slot name="widget-settings"></slot>
this slot seems not used

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/CardComponent.vue
> +      <div>
remove the empty div

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/CardComponent.vue
> +    <oxd-loading-spinner v-if="isLoading" class="orangehrm-container-loader" />
If it its loading, body slot should be hidden.

```
<oxd-loading-spinner v-if="isLoading" class="orangehrm-container-loader" />
<div v-else class="orangehrm-dashboard-widget-body">
  <slot name="body"></slot>
 ...
 ...
</div>
```

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/CardComponent.vue
> +  name: 'WidgetCard',
Rename this component as BaseWidget (BaseWidget.vue)

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/CardComponent.vue
> +      default: '',
Required.

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/CardComponent.vue
> +    widgetName: {
```suggestion
    title: {
```

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/CardComponent.vue
> +    iconName: {
```suggestion
    icon: {
```

2022-08-25 03:52 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/CardComponent.vue
> +@import '@ohrm/oxd/styles/_mixins.scss';
let's move this as separate stylesheet.

2022-08-25 06:36 UTC, Super-Chama requested changes

2022-08-25 06:36 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/BaseWidget.vue
> +      default: '',
title should be required

2022-08-25 06:36 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/BaseWidget.vue
> +    emptyContentText: {
Can we have generic text for this? this prop is not required

2022-08-25 07:27 UTC, Super-Chama approved these changes

2022-08-29 06:05 UTC, RajithaKumara approved these changes

2022-08-29 06:08 UTC, merged