OHRM5X-1683: Employee Time At Work API
orangehrm/orangehrm pull request #1435
Opened 2022-09-05 23:39 UTC by SandeepaOHRM

2022-09-07 06:10 UTC, RajithaKumara requested changes

2022-09-07 06:26 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/config/routes.yaml
> +  path: /api/v2/dashboard/employees/{empNumber}/time-at-work
```suggestion
  path: /api/v2/dashboard/employees/time-at-work
```
will move `empNumber` to query param

2022-09-07 06:26 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/config/routes.yaml
> +    _key: empNumber
```suggestion
    id: 0
```
to go to getOne

2022-09-09 07:13 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeTimeAtWorkAPI.php
> +    public const PARAMETER_EMP_NUMBER = 'empNumber';
done

2022-09-09 07:13 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeTimeAtWorkAPI.php
> +            self::PARAMETER_EMP_NUMBER
done

2022-09-09 07:13 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeTimeAtWorkAPI.php
> +                self::PARAMETER_EMP_NUMBER,
done

2022-09-09 07:13 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Dao/EmployeeTimeAtWorkDao.php
> +            );
done

2022-09-09 07:13 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Dao/EmployeeTimeAtWorkDao.php
> +                ),
yes

2022-09-09 07:14 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Service/EmployeeTimeAtWorkService.php
> +        //TODO::Determine whether current date is server date or date from the client side
done

2022-09-09 07:14 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/config/routes.yaml
> +  path: /api/v2/dashboard/employees/{empNumber}/time-at-work
done

2022-09-09 07:14 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/config/routes.yaml
> +    _key: empNumber
done

2022-09-09 07:51 UTC, RajithaKumara approved these changes

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Dao/EmployeeTimeAtWorkDao.php
> +                ['id' => ListSorter::DESCENDING]
check how sorted in attendance module also. want to check is date also involved

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Dao/EmployeeTimeAtWorkDao.php
> +            )
hope all scenarios covered via tests

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Service/EmployeeTimeAtWorkService.php
> +    private int $totalTimeForWeek = 0;
check this if not refactored yet

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Service/EmployeeTimeAtWorkService.php
> +    private function getTimesheetPeriodService(): TimesheetPeriodService
`private`, above method `public`
it's okay to keep getters public. or make all private if there is no special reason

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Service/EmployeeTimeAtWorkService.php
> +    private function getWeekBoundaryForGivenDate(DateTime $date): array
will reuse the attendance module method if possible. if this method not same as attendance, no need changes

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Service/EmployeeTimeAtWorkService.php
> +            $this->totalTimeForWeek = $this->totalTimeForWeek + $totalTimeForDay;
```suggestion
            $totalTimeForWeek += $totalTimeForDay;
```
```php
    /**
     * @param int $empNumber
     * @param DateTime $currentDateTime
     * @return array
     * @throws Exception
     */
    private function getDataForCurrentWeek(
        int $empNumber,
        DateTime $currentDateTime
    ): array {
        // ...
        $totalTimeForWeek = 0;
        while ($counter < 7) {
            //...
            $totalTimeForWeek +=  $totalTimeForDay;
            $counter++;
        }
        return [$weeklyData, $totalTimeForWeek];
    }
```
if you want to keep `$this->totalTimeForWeek` you can expose only one public method to call from API class.

```php
        list($data, $meta) = $this->getEmployeeTimeAtWorkService()->getTimeAtWork();
        return new EndpointResourceResult(
            ArrayModel::class,
            $data,
            new ParameterBag($meta)
        );
```
```php
    public function getTimeAtWork(/** params */)
    {
        return [
            $this->getEmployeeTimeAtWorkService()->getTimeAtWorkData($empNumber, $currentDateTime),
            $this->getEmployeeTimeAtWorkService()->getTimeAtWorkMetaData($empNumber, $currentDateTime),
    }

    private function getTimeAtWorkData(/** params */) 

    private function getTimeAtWorkMetaData(/** params */) 
```
the reason, why I request to change, other devs don't know they should call `getTimeAtWorkMetaData` after `getTimeAtWorkData` to get correct result.

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/Service/EmployeeTimeAtWorkService.php
> +                'totalTime' => $this->getTimeInHoursAndMinutes($this->totalTimeForWeek)
```suggestion
                'totalTime' => $this->getTimeInHoursAndMinutes($totalTimeForWeek)
```
```php
    public function getTimeAtWorkMetaData(int $empNumber, DateTime $currentDateTime, int $totalTimeForWeek): array
    {
        //...
        return [
            //...
            'currentWeek' => [
               //...
                'totalTime' => $this->getTimeInHoursAndMinutes($totalTimeForWeek)
            ]
        ];
    }
```

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/test/Dao/EmployeeTimeAtWorkDaoTest.php
> +    public function testGetLatestAttendanceRecordByEmpNumber()
```suggestion
    public function testGetLatestAttendanceRecordByEmpNumber(): void
```

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/test/Dao/EmployeeTimeAtWorkDaoTest.php
> +    public function testGetAttendanceRecordsByEmployeeAndDate()
```suggestion
    public function testGetAttendanceRecordsByEmployeeAndDate(): void
```

2022-09-09 07:51 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/test/fixtures/QuickLaunchAPITest3.yml
> +  - {"id": 3,"user_role_id": 3,"emp_number": 3,"user_name": "rajitha","user_password": "$2y$12$f2zH9NNS.GrX/Dmx8r2eWuJt986aPLOUF8LvEj.8aAvFxEmaPIoNa"}
Btw, I don't like to use my name.
use https://github.com/orangehrm/orangehrm/blob/main/src/plugins/orangehrmLeavePlugin/test/fixtures/EmployeeLeaveEntitlementUsageLeaveReportDataAPITest.yaml#L59-L65 kind of dummy data :relaxed:

2022-09-09 07:56 UTC, merged