OHRM5X-1677: Develop Widget - My Actions Summary View [
orangehrm/orangehrm pull request #1448
Opened 2022-09-15 03:01 UTC by SandeepaOHRM

2022-09-15 05:00 UTC, RajithaKumara requested changes

2022-09-16 08:57 UTC, Super-Chama approved these changes

2022-09-16 08:59 UTC, merged

2022-09-16 09:02 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeActionSummaryAPI.php
> +        $leaveRequestSearchFilterParams->setStatuses([Leave::LEAVE_STATUS_LEAVE_PENDING_APPROVAL]);
moved

2022-09-16 09:02 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeActionSummaryAPI.php
> +            ),
done

2022-09-16 09:02 UTC, SandeepaOHRM commented on src/plugins/orangehrmPerformancePlugin/Dao/PerformanceReviewDao.php
> +        if ($performanceReviewSearchFilterParams->isForPendingReviewActionWidget()) {
yes, refactored

2022-09-16 09:02 UTC, SandeepaOHRM commented on src/plugins/orangehrmDashboardPlugin/Api/EmployeeActionSummaryAPI.php
> +        unset($accessibleEmpNumbers[$authUserIndex]);
sure