OHRM5X-1644 : Add notes for language strings
orangehrm/orangehrm pull request #1463
Opened 2022-09-24 08:04 UTC by SharukaNP

2022-09-26 08:12 UTC, RajithaKumara requested changes
Good job :tada:

2022-09-26 08:12 UTC, RajithaKumara commented on installer/Migration/V5_2_0/lang-string/notesForUnitIds.yaml
> +    - { group: performance, note: "Once added, they can be modified.Added and Modified dates are captured automatically.\r\n          Modified date log entries added to the tracker captured automatic
```suggestion
    - { group: performance, note: "Once added, they can be modified. Added and Modified dates are captured automatically. Modified date log entries added to the tracker captured automatically.", unitId: modified_date }
```

2022-09-26 08:12 UTC, RajithaKumara commented on installer/Migration/V5_2_0/lang-string/notesForUnitIds.yaml
> +notesForUnitIds:
```suggestion
notes:
```

2022-09-26 08:12 UTC, RajithaKumara commented on installer/Migration/V5_2_0/Migration.php
> +        $filepath = $filepath = __DIR__ . '/lang-string/notesForUnitIds.yaml';
```suggestion
        $filepath = $filepath = __DIR__ . '/lang-string/notes.yaml';
```

2022-09-26 08:12 UTC, RajithaKumara commented on installer/Migration/V5_2_0/Migration.php
> +        $langStrings = array_shift($yml);
```suggestion
        $langStrings = $yml['notes'];
```
:thinking:

2022-09-30 03:55 UTC, SharukaNP commented on installer/Migration/V5_2_0/Migration.php
> +        $langStrings = array_shift($yml);
This notation won't work.

2022-09-30 03:55 UTC, SharukaNP commented
Checked for special characters and removed them

2022-09-30 06:04 UTC, RajithaKumara approved these changes

2022-09-30 06:05 UTC, merged