OHRM5X-1749: Fix Dashboard and Custom Language Pack Issues
orangehrm/orangehrm pull request #1470
Opened 2022-09-29 09:41 UTC by ManulMax

2022-10-03 09:09 UTC, Super-Chama requested changes

2022-10-03 09:09 UTC, Super-Chama commented on src/client/src/orangehrmDashboardPlugin/components/MyActionSummaryWidget.vue
> +      navigate('/recruitment/viewCandidates?statusId=4');
![image](https://user-images.githubusercontent.com/12880059/193540971-8bc01031-2886-4023-9ef9-74c3a3999a68.png)
@ManulMax I think we specifically discussed not to hardcode like this

2022-10-04 05:36 UTC, Super-Chama commented
[71e29ec](https://github.com/orangehrm/orangehrm/pull/1470/commits/71e29ec4258215c23650578ea79609588cc6d687) was taken to https://github.com/orangehrm/orangehrm/pull/1479

2022-10-04 09:06 UTC, RajithaKumara commented
Closing since moved these fixes to #1480 & #1479

2022-10-04 09:06 UTC, closed without merging