OHRM5X-1331: Fix Language strings marked as not fixable
orangehrm/orangehrm pull request #1486
Opened 2022-10-10 03:00 UTC by ManulMax

2022-10-10 07:38 UTC, RajithaKumara requested changes

2022-10-10 07:38 UTC, RajithaKumara commented on src/client/src/orangehrmAdminPlugin/pages/emailSubscription/EmailSubscription.vue
> +const {$t} = usei18n();
*

2022-10-10 08:04 UTC, Super-Chama requested changes

2022-10-10 08:04 UTC, Super-Chama commented on src/client/src/orangehrmAdminPlugin/pages/emailSubscription/EmailSubscription.vue
> +const {$t} = usei18n();
Discussed before. please use the composables inside setup context

2022-10-10 08:04 UTC, Super-Chama commented on src/client/src/orangehrmAdminPlugin/pages/systemUser/SystemUser.vue
> +          role: _displayName,
`role: item.userRole?.displayName === 'Admin' ? $t('general.admin') : $t('general.ess')`

2022-10-10 08:04 UTC, Super-Chama commented on src/client/src/orangehrmAdminPlugin/pages/emailSubscription/EmailSubscription.vue
> +      _type = `${$t('admin.leave_rejections')}`;
redundant use of back-ticks and template literals. simply use as
`_type = $t('admin.leave_rejections')`

2022-10-10 08:35 UTC, Super-Chama commented on src/client/src/orangehrmTimePlugin/pages/timesheets/ViewEmployeeTimesheet.vue
> +          v-show="timesheetStatus"
Please refactor this to a switch statement/ computed property. don't duplicate the template unnecessarily

2022-10-10 11:13 UTC, Super-Chama requested changes

2022-10-10 11:13 UTC, Super-Chama commented on src/client/src/orangehrmAdminPlugin/pages/emailSubscription/EmailSubscription.vue
> +  const {$t} = usei18n();
move this to setup. move the normaliser into setup as well.

```
setup() {
  const {$t} = usei18n();
  const subscribersNormalizer = data => {
 ....
}
```

2022-10-11 00:23 UTC, Super-Chama approved these changes

2022-10-11 04:26 UTC, RajithaKumara requested changes

2022-10-11 04:26 UTC, RajithaKumara commented on src/client/src/orangehrmPimPlugin/components/SaveEmployeeReportTo.vue
> +      {{ $t('general.add') }} {{ $t('pim.supervisor') }}
don't concatenate lang strings

2022-10-11 04:26 UTC, RajithaKumara commented on src/client/src/orangehrmTimePlugin/components/TimesheetActions.vue
> +            actionName = $t('leave.rejected');
*

2022-10-11 04:26 UTC, RajithaKumara commented on src/plugins/orangehrmDashboardPlugin/test/Dao/ChartDaoTest.php
>          $this->assertEquals(7, $result[2]->getSubunit()->getId());
add test case for the bug fix

2022-10-11 05:25 UTC, RajithaKumara approved these changes

2022-10-11 05:46 UTC, merged