OHRM5X-1813: Develop Buzz -  Create Post API
orangehrm/orangehrm pull request #1526
Opened 2022-11-09 09:56 UTC by ManulMax

2022-11-09 10:13 UTC, ManulMax commented on src/plugins/orangehrmBuzzPlugin/test/fixtures/testcases/BuzzShareAPITestCases.yaml
> +    meta: [ ]
TODO -  add photo post test

2022-11-09 10:22 UTC, ManulMax commented on src/plugins/orangehrmBuzzPlugin/entity/BuzzPost.php
>  class BuzzPost
Refactor to the BuzzText

2022-11-09 10:35 UTC, ManulMax commented on src/plugins/orangehrmBuzzPlugin/Api/BuzzShareAPI.php
> +     */
TODO - Add API Doc for BuzzShareAPI

2022-11-09 10:36 UTC, ManulMax commented on src/plugins/orangehrmBuzzPlugin/Api/EmployeeAnniversaryAPI.php
> +     *     @OA\Parameter(ref="#/components/parameters/limit"),
Change default limit

2022-11-09 11:13 UTC, RajithaKumara requested changes

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/Dao/BuzzDao.php
> +    public function saveBuzzPhotos(BuzzPhoto $buzzPhoto): BuzzPhoto
```suggestion
    public function saveBuzzPhoto(BuzzPhoto $buzzPhoto): BuzzPhoto
```

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/Dao/BuzzDao.php
> +    public function saveBuzzVideo(BuzzLink $buzzVideoPost): BuzzLink
```suggestion
    public function saveBuzzVideo(BuzzLink $buzzVideo): BuzzLink
```

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/Traits/Service/BuzzPostServiceTrait.php
> +trait BuzzPostServiceTrait
delete this trait

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/config/routes.yaml
> +#  methods: [ GET ]
revert this for the moment

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/entity/BuzzPhoto.php
> +        'png',
```suggestion
        'png',
        'jfif',
```

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/entity/Decorator/BuzzPostDecorator.php
> +    public function getBuzzPost(): BuzzPost
```suggestion
    protected function getBuzzPost(): BuzzPost
```

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/entity/Decorator/BuzzPostDecorator.php
> +        $this->buzzPost->setEmployee($employee);
```suggestion
        $this->getBuzzPost()->setEmployee($employee);
```

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/entity/Decorator/BuzzShareDecorator.php
> +    public function getBuzzShare(): BuzzShare
```suggestion
    protected function getBuzzShare(): BuzzShare
```

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/test/Dao/BuzzDaoTest.php
> +        $buzzPhoto->setPhoto('iVBORw0KGgoAAAANSUhEUgAAA2wAAAINCAYAAABCs/waAAAABmJLR0QA/wD/AP+gvaeTAAB13klEQVR42uydB5hcVfXAE7p0KVIU6V0RRUAQsIAiCCrIWgiJWychuOy8mdmEojBSkuy8O7NhNWgoFkDFIPxBOkgRERAREBSQ3
you can put a image inside fixture folder and read it

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/test/Dao/BuzzDaoTest.php
> +        $dateTimeHelper = $this->getMockBuilder(DateTimeHelperService::class)
??
I feel should move to setup

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmPimPlugin/entity/Employee.php
> +    }
remove

2022-11-09 11:13 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/Api/BuzzShareAPI.php
> +    use BuzzPostServiceTrait;
```suggestion
    use BuzzServiceTrait;
```

2022-11-09 12:14 UTC, merged

2022-11-10 10:26 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/entity/BuzzPost.php
>  class BuzzPost
Will skip this