OHRM5X-1814: Develop Buzz - Update Post API
orangehrm/orangehrm pull request #1556
Opened 2022-12-02 04:58 UTC by ManulMax

2022-12-03 06:00 UTC, RajithaKumara requested changes

2022-12-03 06:00 UTC, RajithaKumara commented on src/plugins/orangehrmBuzzPlugin/test/Api/BuzzPostAPITest.php
> +    public function dataProviderForTestUpdate()
```suggestion
    public function dataProviderForTestUpdate(): array
```

2022-12-05 04:14 UTC, ManulMax commented on src/plugins/orangehrmBuzzPlugin/Dto/BuzzVideoURL/BuzzVideoURL.php
> +interface BuzzVideoURL
No, Not sure how this came here

2022-12-05 04:14 UTC, ManulMax commented on src/plugins/orangehrmBuzzPlugin/Dto/BuzzVideoURL/BuzzVideoURL.php
> +interface BuzzVideoURL
No, Not sure how this came here

2022-12-05 04:17 UTC, ManulMax commented on src/plugins/orangehrmBuzzPlugin/Api/BuzzURLValidationAPI.php
> +class BuzzURLValidationAPI extends Endpoint implements CollectionEndpoint
No this also come accidentally

2022-12-05 06:16 UTC, ManulMax commented on src/plugins/orangehrmBuzzPlugin/Api/BuzzPostAPI.php
> +            new Rule(Rules::REQUIRED),
TODO

2022-12-06 08:08 UTC, RajithaKumara requested changes

2022-12-06 10:55 UTC, merged