OHRM5X-1931: Develop claim - create claim event API
orangehrm/orangehrm pull request #1587
Opened 2023-01-04 11:46 UTC by DulsaraNethmin

2023-01-04 11:53 UTC, RajithaKumara requested changes

2023-01-04 11:53 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +    public function delete(): EndpointResult
add doc comments for all methods

2023-01-04 11:53 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     * @throws TransactionException
```suggestion
     * @inheritDoc
```

2023-01-04 11:53 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/test/fixtures/ClaimEvent.yaml
> +  3: { id: 4, name: "event4", description: "event4 desc" }
add new line

2023-01-04 11:53 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/test/Api/ClaimEventAPITest.php
> +}
add new line

2023-01-04 11:53 UTC, RajithaKumara commented on src/lib/orm/Doctrine.php
> +        return true;
revert this

2023-01-05 05:57 UTC, ManulMax requested changes
> Good First PR. Will do necessary changes and make it Perfect.

2023-01-05 05:57 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Traits/Service/ClaimEventTrait.php
> +trait ClaimEventTrait
`ClaimServiceTrait`

2023-01-05 05:57 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +
Remove unnecessary space

2023-01-05 05:57 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Dto/ClaimEventSearchFilterParams.php
> +    public const ALLOWED_SORT_FIELDS = ['ce.name','ce.status'];
change ce to meaningful name

2023-01-05 05:57 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Service/ClaimService.php
> +     * @throws DaoException
remove `@throws DaoException`

2023-01-05 05:57 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Service/ClaimService.php
> +     * @throws DaoException
remove `@throws DaoException`

2023-01-05 05:57 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Service/ClaimService.php
> +use OrangeHRM\Core\Exception\DaoException;
remove `DaoException`

2023-01-05 05:57 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     * @return void
remove `@return void`

2023-01-05 05:57 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimEventDao.php
> +     * @throws DaoException
remove `@throws DaoException`

2023-01-10 02:51 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +        $this->getClaimEventService()->getClaimEventDao()->saveEvent($claimEvent);
Same event cannot add multiple times. 
_"Already Exists" validation should show up when trying to save an event that is already present in the list_

2023-01-10 02:55 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +                new Rule(Rules::STRING_TYPE)
Should change to Positive

2023-01-10 02:56 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +                new Rule(Rules::STRING_TYPE)
Should validate length

2023-01-10 03:31 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimEventDao.php
> +        $q->distinct();
Since we not allow to add multiple records we don't need this ???

2023-01-10 03:33 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimEventDao.php
> +            $q->andWhere('claimEvent.name = :name');
`$q->expr()->like`

2023-01-10 03:45 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Service/ClaimService.php
> +    }
seems like not using ?

2023-01-10 03:46 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Service/ClaimService.php
> +    }
this one also seems like not using.

2023-01-10 03:47 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Service/ClaimService.php
> +}
Check these too

2023-01-10 06:54 UTC, merged