OHRM5X-1942: Create Claim Expense Type API
orangehrm/orangehrm pull request #1598
Opened 2023-01-16 05:12 UTC by ManulMax

2023-01-16 05:15 UTC, ManulMax commented on installer/Migration/V5_4_0/Migration.php
> +        }
Have to change and add Alter table

2023-01-16 05:58 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimExpenseTypesAPI.php
> +     */
Need to add API doc

2023-01-18 03:17 UTC, RajithaKumara requested changes

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimExpenseTypesAPI.php
> +     */
please add API doc

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimExpenseTypesAPI.php
> +            ),
*

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimExpenseTypesAPI.php
> +                    new Rule(Rules::BOOL_TYPE)
```suggestion
                    new Rule(Rules::BOOL_VAL)
```
:thinking:

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimExpenseTypesAPI.php
> +        $expenseType->getDecorator()->setUserByUserId($userId);
```suggestion
        $expenseType->getDecorator()->setUserByUserId($this->getAuthUser()->getUserId());
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimRequestAPI.php
> +     * @throws InvalidParamException
```suggestion
```

API doc

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimRequestAPI.php
> +                new Rule(Rules::REQUIRED)
are we expecting id?

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimRequestAPI.php
> +            $claimRequest->setCurrency($currencyId);
This seems wrong. you should set the currency object, not the id. check entity

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimRequestAPI.php
> +            $referenceId = date('Ymd') . str_pad("$nextId", 7, 0, STR_PAD_LEFT);
move this to service method

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimExpenseTypesModel.php
> +class ClaimExpenseTypesModel implements Normalizable
```suggestion
class ClaimExpenseTypeModel implements Normalizable
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimRequestModel.php
> +                'currency',
is this currency id?
better to go like this
```json
currency: {
    id: 
    ...
}
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +        return $id[0][1];
want to recheck this

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/config/routes.yaml
> +  path: /api/v2/claim/expense/types
```suggestion
  path: /api/v2/claim/expenses/types
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/config/routes.yaml
> +    _api: OrangeHRM\Claim\Api\ClaimExpenseTypesAPI
```suggestion
    _api: OrangeHRM\Claim\Api\ClaimExpenseTypeAPI
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/config/routes.yaml
> +  path: /api/v2/claim/request
```suggestion
  path: /api/v2/claim/requests
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/config/routes.yaml
> +apiv2_claim_request:
```suggestion
apiv2_claim_requests:
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/entity/ClaimRequest.php
> +use OrangeHRM\Claim\entity\Decorator\ClaimRequestDecorator;
```suggestion
use OrangeHRM\Entity\Decorator\ClaimRequestDecorator;
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/entity/ClaimRequest.php
> +    private ?string $description;
```suggestion
    private ?string $description = null;
```

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/entity/ClaimRequest.php
> +     * @ORM\Column(name="currency", type="string", length=3)
isn't this a relational column

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/entity/Expense.php
> +class Expense
is this relevant to this PR?

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/test/Api/ClaimExpenseTypesAPITest.php
> +class ClaimExpenseTypesAPITest extends EndpointIntegrationTestCase
```suggestion
class ClaimExpenseTypeAPITest extends EndpointIntegrationTestCase
```
add groups

2023-01-18 03:17 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/test/Api/ClaimRequestAPITest.php
> +class ClaimRequestAPITest extends EndpointIntegrationTestCase
add groups

2023-01-18 04:08 UTC, merged

2023-01-18 08:18 UTC, ManulMax commented on installer/Migration/V5_4_0/Migration.php
> +        }
add to migration

2023-01-18 08:18 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimExpenseTypesAPI.php
> +     */
added