OHRM5X-2001: Claim event filter form
orangehrm/orangehrm pull request #1600
Opened 2023-01-18 10:41 UTC by DulsaraNethmin

2023-01-23 11:45 UTC, ManulMax commented on installer/Migration/V5_4_0/Migration.php
> +                        ->executeStatement();
need to check this twise

2023-01-24 08:46 UTC, ManulMax commented on installer/Migration/V5_4_0/Migration.php
> +
can remove this and implement according to the `changeClaimExpenseTypeTableStatusToBoolean` after rebasing

2023-01-24 08:46 UTC, ManulMax commented on installer/Migration/V5_4_0/Migration.php
> +                        ->executeStatement();
implement according to the changeClaimExpenseTypeTableStatusToBoolean after rebasing

2023-01-24 12:07 UTC, RajithaKumara requested changes

2023-01-24 12:07 UTC, RajithaKumara commented on src/client/src/orangehrmClaimPlugin/pages/ClaimEvent.vue
> +      {id: 0, label: 'Disabled'},
i18n

2023-01-24 12:07 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     *     tags={"Claim/Claim Events"},
```suggestion
     *     tags={"Claim/Events"},
```
@ManulMax what do you think?

2023-01-25 03:53 UTC, Super-Chama requested changes

2023-01-25 03:53 UTC, Super-Chama commented on installer/Migration/V5_4_0/lang-string/claim.yaml
> +    unitId: events
add new line in the end

2023-01-25 03:53 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/ClaimEvent.vue
> +    items_new() {
you can use a `normalizer` function as a parameter for `usePaginate` function. `normalizer` is a function that can transform raw data retrived via API before getting output.

https://github.com/orangehrm/orangehrm/blob/main/src/client/src/orangehrmAdminPlugin/pages/systemUser/SystemUser.vue#L200

2023-01-25 03:53 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/ClaimEvent.vue
> +              onClick: () => {
`onClick: this.onClickDelete`

2023-01-25 03:53 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/ClaimEvent.vue
> +              onClick: () => {
implement a dummy method with body as `//TODO`

2023-01-25 03:53 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/ClaimEvent.vue
> +      this.filter2 = null;
`filter2` seems unused

2023-01-25 03:53 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/ClaimEvent.vue
> +          //this.deleteItems([item.id]);
not implemented?

2023-01-25 03:53 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/ClaimEvent.vue
> +<style></style>
remove empty block

2023-01-25 03:53 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/ClaimEvent.vue
> +  <oxd-table-filter filter-title="Events">
Events should be i18n string

2023-01-25 03:53 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/index.ts
> +import SaveClaimEvent from '@/orangehrmClaimPlugin/pages/SaveClaimEvent.vue';
this file is missing?

2023-01-25 04:35 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     *     tags={"Claim/Claim Events"},
tags={"Claim/Events"}, is better

2023-01-25 04:40 UTC, DulsaraNethmin commented on src/client/src/orangehrmClaimPlugin/index.ts
> +import SaveClaimEvent from '@/orangehrmClaimPlugin/pages/SaveClaimEvent.vue';
i didn't commit it

2023-01-25 06:29 UTC, ManulMax requested changes

2023-01-25 06:29 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/test/Api/ClaimExpenseTypeAPITest.php
> +
remove this

2023-01-25 06:29 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/test/Api/ClaimRequestAPITest.php
> - */
don't remove these codes

2023-01-25 06:29 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     *     tags={"Claim/Claim Events"},
change this tags according to the feedback

2023-01-25 06:29 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     *     tags={"Claim/Claim Events"},
tags={"Claim/Events"},

2023-01-25 06:29 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     *     tags={"Claim/Claim Events"},
tags={"Claim/Events"},

2023-01-25 09:01 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     *             )
```suggestion
```

2023-01-25 09:02 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
>       * @throws RecordNotFoundException
```suggestion
```

2023-01-25 09:05 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimEventModel.php
>  class ClaimEventModel implements Normalizable
expose `deleted` parameter as well

2023-01-25 09:09 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimEventModel.php
>  class ClaimEventModel implements Normalizable
ref: src/plugins/orangehrmLeavePlugin/Api/Model/LeaveTypeModel.php

2023-01-25 09:14 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     *     @OA\Parameter(ref="#/components/parameters/offset"),
`eventId` test scenarios

1. zero
2. existing id
3. non-existing id
4. try deleted id

2023-01-25 09:14 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimEventModel.php
>  class ClaimEventModel implements Normalizable
No need to handle this

2023-01-26 02:28 UTC, RajithaKumara requested changes

2023-01-26 02:28 UTC, RajithaKumara commented on installer/Migration/V5_4_0/lang-string/claim.yaml
> +    unitId: events
this feedback not addressed

2023-01-26 02:28 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +    public const PARAMETER_CLAIMID = 'claimId';
```suggestion
    public const PARAMETER_EVENT_ID = 'eventId';
```
refactor this

2023-01-26 02:28 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
>      public const PARAMETER_ID = 'id';
@ManulMax can use from common parms

2023-01-26 02:28 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +     *     @OA\Parameter(ref="#/components/parameters/offset"),
not addressed

2023-01-26 02:28 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +                    )
```suggestion
                    new Rule(Rules::POSITIVE)
```

2023-01-26 02:28 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dto/ClaimEventSearchFilterParams.php
> +    public const ALLOWED_SORT_FIELDS = ['claimEvent.name','claimEvent.status','claimEvent.id'];
```suggestion
    public const ALLOWED_SORT_FIELDS = ['claimEvent.name','claimEvent.status'];
```
remove `claimEvent.id`

2023-01-26 02:28 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/test/fixtures/ClaimEvent.yml
> +  0: { id: 1, name: "event1", description: "event1 desc", status: true, is_deleted: false}
prefer if you can define meaningful data

2023-01-26 02:36 UTC, merged