OHRM5X-2084: Develop - Claim request attachment API
orangehrm/orangehrm pull request #1630
Opened 2023-02-27 17:19 UTC by DulsaraNethmin

2023-02-28 14:44 UTC, ManulMax requested changes

2023-02-28 14:44 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimAttachmentAPI.php
> +            $claimAttachment->getDecorator()->setUserByUserId($userId);
```suggestion
            $claimAttachment->getDecorator()->setUserByUserId($this->getAuthUser()->getUserId());
```

2023-02-28 14:44 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +        dump($id[0][1]);
```suggestion
```

?????

2023-03-01 03:10 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimAttachmentAPI.php
> +     *         in="attribute",
if `requestId` in the URL `in="attribute"` is correct

2023-03-01 03:13 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimAttachmentModel.php
>                  'attachmentId',
```suggestion
                'id',
```

2023-03-01 05:18 UTC, ManulMax requested changes

2023-03-03 08:20 UTC, RajithaKumara requested changes

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimExpenseAPI.php
> +            );
```suggestion
            $claimExpense->getDecorator()->setExpenseTypeByExpenseTypeId($expenseTypeId);
```

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimAttachmentModel.php
> +     */
move this doc comment on to class

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimAttachmentModel.php
> +                'fileDescription',
```suggestion
                'description',
```

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimAttachmentModel.php
> +                'date'
is this formatted, seems not used decorator

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimExpenseModel.php
> +
remove this line

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +    public function deleteClaimExpense(ClaimRequest $claimRequest, array $ids): int
```suggestion
    public function deleteClaimExpense(int $claimRequestId, array $ids): int
```
shall we go like this :thinking: 
Also update function's doc comment

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +            ->select('MAX(attachment.attachId)')
```suggestion
        $q = $this->createQueryBuilder(ClaimAttachment::class, 'attachment');
        $q->select($q->expr()->max('attachment.attachId')
```

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +        return $id[0][1];
```suggestion
        $id = $q->getQuery()->getSingleScalarResult();
        $id = $id === null ? 0 : intval($id);
        return ++$id;
```

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +        return $this->getPaginator($q)->getQuery()->execute()[0][1];
```suggestion
        $q = $this->createQueryBuilder(ClaimAttachment::class, 'claimAttachment');
        $this->setSortingAndPaginationParams($q, $claimAttachmentSearchFilterParams);
        if (!is_null($claimAttachmentSearchFilterParams->getRequestId())) {
            $q->andWhere('claimAttachment.requestId = :requestId');
            $q->setParameter('requestId', $claimAttachmentSearchFilterParams->getRequestId());
        }
        return $this->getPaginator($q)->count();
```

2023-03-03 08:20 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dto/ClaimAttachmentSearchFilterParams.php
> +{
allowed sort fields not defined

2023-03-03 08:46 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimAttachmentAPI.php
> +     *         )
use ref `#/components/schemas/Base64Attachment`

2023-03-03 08:50 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimAttachmentAPI.php
> +            if ($attachment) {
```suggestion
            if ($attachment instanceof Base64Attachment) {
```

2023-03-03 08:50 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/ClaimAttachmentAPI.php
> +            if ($attachment) {
```suggestion
            if ($attachment instanceof Base64Attachment) {
```

2023-03-03 09:36 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimAttachmentModel.php
> +                'date'
check `src/plugins/orangehrmAttendancePlugin/Api/Model/AttendanceRecordModel.php` for employee object

2023-03-08 03:49 UTC, ManulMax requested changes

2023-03-08 04:22 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimAttachmentModel.php
> + *     )
@OA\Property(property="date", type="string", format="date"),

2023-03-08 04:24 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/Model/ClaimAttachmentModel.php
> + *         property="Employee",
```suggestion
 *         property="employee",
```

2023-03-08 10:01 UTC, RajithaKumara approved these changes

2023-03-08 10:03 UTC, merged