OHRM5X-2085: Handle Claim workflow states
orangehrm/orangehrm pull request #1637
Opened 2023-03-09 00:34 UTC by DulsaraNethmin

2023-03-14 03:51 UTC, ManulMax requested changes

2023-03-14 03:51 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Api/ClaimAttachmentAPI.php
> +    ];
seems like not using

2023-03-15 03:51 UTC, RajithaKumara approved these changes

2023-03-15 03:51 UTC, RajithaKumara commented on installer/Migration/V5_4_0/Migration.php
>      private function modifyClaimTables(): void
TODO::
change `ohrm_claim_request` status from TEXT to VARCHAR

2023-03-15 03:51 UTC, RajithaKumara commented on installer/Migration/V5_4_0/Migration.php
> +        string $menu_title,
```suggestion
        string $menuTitle,
```
use camelCase

2023-03-15 03:51 UTC, RajithaKumara commented on installer/Migration/V5_4_0/Migration.php
> +        string $rolesToNotify,
remove this parameter as all method call used empty string

2023-03-15 03:51 UTC, RajithaKumara commented on installer/Migration/V5_4_0/Migration.php
> +            ->setParameter('rolesToNotify', $rolesToNotify)
```suggestion
            ->setParameter('rolesToNotify', '')
```

2023-03-15 03:51 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/entity/ClaimRequest.php
>       * @ORM\Column(name="status", type="string", length=255)
Modify migration to consistent with VARCHAR

2023-03-15 03:51 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/test/fixtures/ClaimAttachment.yaml
>  ClaimAttachment:
in attachment table `eattach_attachment` column we are storing data as blobs, not as base64 encoded

2023-03-15 03:52 UTC, merged