OHRM5X-2066: Develop oauth - consent screen FE
orangehrm/orangehrm pull request #1641
Opened 2023-03-12 21:50 UTC by devishke-orange

PR contains:
- OHRM5X-2066: [FE] Develop consent screen

Mobile View
![image](https://user-images.githubusercontent.com/97493184/224575655-ed9ebf50-eaf3-4e7d-9891-6bccb900c1fd.png)

Mobile View - Invalid Request
![image](https://user-images.githubusercontent.com/97493184/224575678-e43e5049-4835-46c3-a61f-1a7f1a312773.png)

Web View
![image](https://user-images.githubusercontent.com/97493184/224575727-ef104644-52ae-42d3-9f92-15aa8ef24e92.png)

Web View - Invalid Request
![image](https://user-images.githubusercontent.com/97493184/224575699-c7ef1b53-0075-49b8-a14f-ab698359dfa0.png)

2023-03-12 21:51 UTC, devishke-orange commented
Example Google OAuth Error Screens:
![image](https://user-images.githubusercontent.com/97493184/224575804-9d4fdde6-5fb4-4a8f-98e5-e20808addc72.png)

![image](https://user-images.githubusercontent.com/97493184/224575814-e0db65d8-92ec-43b5-9a4f-57c783d82f91.png)

2023-03-13 10:51 UTC, RajithaKumara requested changes

2023-03-13 10:51 UTC, RajithaKumara commented on installer/Migration/V5_4_0/lang-string/auth.yaml
> +    unitId: access_your_basic_profile_info
I feel this point already covered under `Access and manage your data`

2023-03-13 10:51 UTC, RajithaKumara commented on installer/Migration/V5_4_0/lang-string/auth.yaml
> +    unitId: keep_you_signed_in_to_the_app
Will remove this

2023-03-13 10:51 UTC, RajithaKumara commented on installer/Migration/V5_4_0/lang-string/auth.yaml
> +    unitId: perform_requests_on_your_behalf
```suggestion
    value: 'Perform actions on your behalf'
    unitId: perform_actions_on_your_behalf
```
:thinking:

2023-03-13 10:51 UTC, RajithaKumara commented on src/client/src/orangehrmCoreOAuthPlugin/pages/oauth/oauth-authorize.scss
> +.orangehrm-oauth {
According to `Web View` SS, seems we can allocate more width for the card.
Hope the design similar to Maintenance Admin access and Forgot password screens

2023-03-13 11:43 UTC, devishke-orange commented
Updated SS:

Mobile View
![image](https://user-images.githubusercontent.com/97493184/224692109-c98f1f7a-e436-43ed-aeb8-bbe44945ed84.png)

Mobile View - Invalid Request
![image](https://user-images.githubusercontent.com/97493184/224692320-a30951ed-341a-4329-9184-034cbf7be9cb.png)

Web View
![image](https://user-images.githubusercontent.com/97493184/224692211-4823d2eb-91c6-4add-a2a6-73b0dc9450d4.png)

Web View - Invalid Request
![image](https://user-images.githubusercontent.com/97493184/224692262-00a35a17-fb00-4301-85ea-4f57039942ae.png)

2023-03-13 13:42 UTC, merged