OHRM5X-2048: Develop create claim request screen
orangehrm/orangehrm pull request #1643
Opened 2023-03-16 00:40 UTC by DulsaraNethmin

2023-03-16 09:26 UTC, Super-Chama requested changes

2023-03-16 09:26 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/submitClaim/SubmitClaim.vue
> +        return {
Form submission will happen only one time but this computed property will re run for every update, i don't think we need a computed property. transform the value before being send

2023-03-16 09:26 UTC, Super-Chama commented on installer/Migration/V5_4_0/lang-string/claim.yaml
> +    value: "Create"
please check and confirm if this lang string value is not defined before

2023-03-16 09:27 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/submitClaim/SubmitClaim.vue
> +          ...this.computedRequest,
not a good use. looks a case of premature optimisation

2023-03-16 09:28 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/submitClaim/SubmitClaim.vue
> +    computedRequest() {
Agree. best to just transform and send because submit will only happen once

2023-03-16 13:16 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/submitClaim/SubmitClaim.vue
> +  event: {},
```suggestion
  event: null,
```

2023-03-16 13:17 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/pages/submitClaim/SubmitClaim.vue
> +    getResponse() {
why define a method if it's called in multiple places?

2023-03-17 05:46 UTC, Super-Chama commented on src/client/src/orangehrmClaimPlugin/index.ts
> +  'submit-claim': SubmitClaim,
```suggestion
  'submit-claim-request': SubmitClaimRequest,
```

2023-03-21 05:52 UTC, RajithaKumara approved these changes

2023-03-21 05:52 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +    public function getValidationRuleForCreate(): ParamRuleCollection //TODO: Add employee number
TODO

2023-03-21 05:52 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +    protected function setClaimRequest(ClaimRequest $claimRequest, ?int $empNumber = null): ClaimRequest
```suggestion
    protected function setClaimRequest(ClaimRequest $claimRequest, int $empNumber): ClaimRequest
```
better to make this parameter mandatory in next PR

2023-03-21 05:52 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/MyClaimRequestAPI.php
> +        $id = $this->getRequestParams()->getInt(RequestParams::PARAM_TYPE_ATTRIBUTE, CommonParams::PARAMETER_ID);
seems not handled access control. anyone can access any claim request

2023-03-21 05:52 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +        return ++$id;
:ok_hand:

2023-03-21 05:52 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/config/routes.yaml
> +  path: /api/v2/claim/employee/{empNumber}/requests
```suggestion
  path: /api/v2/claim/employees/{empNumber}/requests
```
use plural

2023-03-21 05:52 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/config/routes.yaml
> +  path: /api/v2/claim/employee/{empNumber}/requests/{id}
```suggestion
  path: /api/v2/claim/employees/{empNumber}/requests/{id}
```

2023-03-21 05:54 UTC, RajithaKumara commented on installer/Migration/V5_4_0/Migration.php
> +                ->setParameter('user_role_id', $this->getDataGroupHelper()->getUserRoleIdByName('Ess'))
```suggestion
                ->setParameter('user_role_id', $this->getDataGroupHelper()->getUserRoleIdByName('ESS'))
```

2023-03-21 05:54 UTC, RajithaKumara commented on installer/Migration/V5_4_0/Migration.php
> +                ->setParameter('action', 'claim/submitClaim')
TODO:: change to my claim

2023-03-21 05:57 UTC, merged