OHRM5X-1959: Develop ClaimRequest getAll API
orangehrm/orangehrm pull request #1656
Opened 2023-03-28 00:34 UTC by DulsaraNethmin

2023-03-31 09:51 UTC, ManulMax requested changes

2023-04-10 10:43 UTC, RajithaKumara approved these changes

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
>          WorkflowStateMachine::CLAIM_ACTION_APPROVE => 'APPROVE',
```php
    public const PARAMETER_CLAIM_EVENT_ID = 'claimEventId';
    public const PARAMETER_CURRENCY_ID = 'currencyId';
    public const PARAMETER_REMARKS = 'remarks';
    public const PARAMETER_ALLOWED_ACTIONS = 'allowedActions';
    public const PARAMETER_EMPLOYEE_NUMBER = 'empNumber';
    public const PARAMETER_REFERENCE_ID = 'referenceId';
    public const PARAMETER_EVENT_ID = 'eventId';
    public const PARAMETER_STATUS = 'status';
    public const PARAMETER_FROM_DATE = 'fromDate';
    public const PARAMETER_TO_DATE = 'toDate';

    public const REMARKS_MAX_LENGTH = 1000;

    public const ACTIONABLE_STATES_MAP = [
        WorkflowStateMachine::CLAIM_ACTION_SUBMIT => 'SUBMIT',
        WorkflowStateMachine::CLAIM_ACTION_APPROVE => 'APPROVE',
        WorkflowStateMachine::CLAIM_ACTION_PAY => 'PAY',
        WorkflowStateMachine::CLAIM_ACTION_CANCEL => 'CANCEL',
        WorkflowStateMachine::CLAIM_ACTION_REJECT => 'REJECT'
];
```
prefer if you can organize

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
>      public const PARAMETER_EMPLOYEE_NUMBER = 'empNumber';
can use from common params

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +     * @param array $claimRequests
```suggestion
     * @param ClaimRequest[] $claimRequests
```
:thinking:

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +            }
bit confusing

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +        );
any idea to validate toDate > fromDate

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +                    new Rule(Rules::STRING_TYPE)
```suggestion
                    new Rule(Rules::IN, [array_values(self::ACTIONABLE_STATES_MAP)]),
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +                    new Rule(Rules::DATE_TIME)
```suggestion
                    new Rule(Rules::API_DATE)
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +                    new Rule(Rules::DATE_TIME)
```suggestion
                    new Rule(Rules::API_DATE)
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +                    new Rule(Rules::POSITIVE)
```suggestion
                    new Rule(Rules::IN_ACCESSIBLE_ENTITY_ID, [Employee::class])
```
:thinking:

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/Model/MyClaimRequestModel.php
> +class MyClaimRequestModel implements Normalizable
I feel better to reuse `EmployeeClaimRequestModel`.  will discuss this

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/MyClaimRequestAPI.php
> +            MyClaimRequestModel::class,
```suggestion
            EmployeeClaimRequestModel::class,
```
will discuss this

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +    protected function getClaimRequestPaginator(ClaimRequestSearchFilterParams $myClaimRequestSearchFilterParams): Paginator
```suggestion
    protected function getClaimRequestPaginator(ClaimRequestSearchFilterParams $claimRequestSearchFilterParams): Paginator
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +    public function getClaimRequestCount(ClaimRequestSearchFilterParams $myClaimRequestSearchFilterParams): int
```suggestion
    public function getClaimRequestCount(ClaimRequestSearchFilterParams $claimRequestSearchFilterParams): int
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dto/ClaimRequestSearchFilterParams.php
> +        $this->setSortOrder('DESC');
```suggestion
        $this->setSortOrder(ListSorter::DESCENDING);
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dto/ClaimRequestSearchFilterParams.php
> +     * @return array|null
```suggestion
     * @return int[]|null
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dto/ClaimRequestSearchFilterParams.php
> +     * @param array|null $empNumbers
```suggestion
     * @param int[]|null $empNumbers
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/entity/ClaimRequest.php
>       * @ORM\Column(name="submitted_date", type="datetime")
```suggestion
     * @ORM\Column(name="submitted_date", type="datetime", nullable=true)
```

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/entity/Decorator/ClaimRequestDecorator.php
> +        if (is_null($totalExpense)) {
is this covered by unit tests?

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/entity/Decorator/ClaimRequestDecorator.php
> +    public function getTotalExpense(): float
is there any other way to improve this. since if you have 50 items in API response then, this will call 50 times

2023-04-10 10:43 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/test/fixtures/testcases/EmployeeClaimRequestAPITestCases.yaml
> +            "name": "Travel Expenses"
need to check whether we need claim event `status` also in the response

2023-04-10 10:44 UTC, merged