OHRM5X-2120: Add new detailed model for MyInfoAPI
orangehrm/orangehrm pull request #1657
Opened 2023-03-28 04:15 UTC by ManulMax

2023-03-29 05:51 UTC, ManulMax commented on src/plugins/orangehrmPimPlugin/Api/Model/MyInfoDetailedModel.php
> +                'lastName',
add empNumber

2023-03-29 05:53 UTC, ManulMax commented on src/plugins/orangehrmPimPlugin/Api/MyInfoAPI.php
>          self::MODEL_DEFAULT => EmployeeModel::class,
Add EmployeeDetailedModel

2023-03-29 13:47 UTC, RajithaKumara requested changes

2023-03-29 13:47 UTC, RajithaKumara commented on src/plugins/orangehrmPimPlugin/Api/MyInfoAPI.php
> +    public const MODEL_SUMMERY = 'summery';
```suggestion
    public const MODEL_SUMMARY = 'summary';
```
typo

2023-03-29 13:47 UTC, RajithaKumara commented on src/plugins/orangehrmPimPlugin/Api/MyInfoAPI.php
> +     *             enum={OrangeHRM\Pim\Api\MyInfoAPI::MODEL_DEFAULT, OrangeHRM\Pim\Api\MyInfoAPI::MODEL_DETAILED, },
```suggestion
     *             enum={OrangeHRM\Pim\Api\MyInfoAPI::MODEL_DEFAULT, OrangeHRM\Pim\Api\MyInfoAPI::MODEL_DETAILED, OrangeHRM\Api\MyInfoAPI::MODEL_SUMMARY},
```

2023-03-30 08:03 UTC, RajithaKumara approved these changes

2023-03-30 08:09 UTC, merged