OHRM5X-2127: Add API to get Menu Items for Mobile
orangehrm/orangehrm pull request #1658
Opened 2023-04-03 22:06 UTC by ManulMax

2023-04-11 13:55 UTC, RajithaKumara requested changes

2023-04-11 13:55 UTC, RajithaKumara commented on src/composer.json
> +            "OrangeHRM\\Tests\\Claim\\": "./plugins/orangehrmClaimPlugin/test",
```suggestion
```
remove this line

2023-04-11 13:55 UTC, RajithaKumara commented on src/composer.json
> +            "OrangeHRM\\Claim\\": "./plugins/orangehrmClaimPlugin",
```suggestion
```
remove this line, as claim moved to 5.5 branch

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmAttendancePlugin/Api/EmployeeAttendanceSummaryAPI.php
> +    public const  PARAMETER_FROM_DATE = 'fromDate';
```suggestion
    public const PARAMETER_FROM_DATE = 'fromDate';
```
:relaxed:

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmAttendancePlugin/Api/EmployeeAttendanceSummaryAPI.php
> +        if ($fromDate != null && $toDate != null && strtotime($fromDate) > strtotime($toDate)) {
*

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmAttendancePlugin/test/fixtures/testcases/EmployeeAttendanceSummaryAPITestCases.yaml
> +      message: 'Invalid Parameter'
better to validate using `invalidOnly` attribute

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveAPI.php
> +        // TODO:: filter by status
TODO

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveAPI.php
> +//            throw $this->getInvalidParamException(["fromDate","toDate"]);
TODO

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveAPI.php
> +            ...$this->getSortingAndPaginationParamsRules(LeaveRequestSearchFilterParams::ALLOWED_SORT_FIELDS) // TODO:: replace with correct class
TODO

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php
> +    public function getLeavesFilterByDateRange(
do we need this?

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/config/routes.yaml
> +  path: /api/v2/leave/employees/{empNumber}/leaves
```suggestion
  path: /api/v2/leave/employees/leaves
```
:thinking: will go like this, we can utilize for my attendance also

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveAPI.php
> +            RequestParams::PARAM_TYPE_ATTRIBUTE,
```suggestion
            RequestParams::PARAM_TYPE_QUERY,
```

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmLeavePlugin/test/Api/EmployeeLeaveAPITest.php
> +namespace Api;
```suggestion
namespace OrangeHRM\Tests\Leave\Api;
```

2023-04-11 13:55 UTC, RajithaKumara commented on src/plugins/orangehrmMobilePlugin/Api/MenuItemAPI.php
> +     *     path="/api/v2/mobile/modules",
change URL

2023-04-18 03:00 UTC, RajithaKumara requested changes

2023-04-18 06:59 UTC, merged

2023-04-20 04:12 UTC, ManulMax commented on src/plugins/orangehrmMobilePlugin/test/fixtures/testcases/MenuItemAPITestCases.yaml
> +        ]
sure

2023-04-20 05:33 UTC, ManulMax commented on src/plugins/orangehrmMobilePlugin/test/Api/MenuItemAPITest.php
> +    public function testGetOne3(TestCaseParams $testCaseParams): void
added to PR - https://github.com/orangehrm/orangehrm/pull/1669

2023-04-20 05:34 UTC, ManulMax commented on src/plugins/orangehrmMobilePlugin/test/fixtures/testcases/MenuItemAPITestCases.yaml
> +        ]
added to PR - https://github.com/orangehrm/orangehrm/pull/1669