OHRM5X-2052: Develop Assign Claim screen
orangehrm/orangehrm pull request #1688
Opened 2023-05-15 02:54 UTC by DulsaraNethmin

2023-05-15 22:03 UTC, ManulMax requested changes

2023-05-15 22:03 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/Controller/AssignClaimRequestController.php
> +            )
```suggestion
!$claimRequest instanceof ClaimRequest
            || $this->getUserRoleManagerHelper()->isSelfByEmpNumber($claimRequest->getEmployee()->getEmpNumber())
            || !$this->getUserRoleManagerHelper()->isEmployeeAccessible($claimRequest->getEmployee()->getEmpNumber())
```
Format code

2023-05-15 22:03 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/config/routes.yaml
> +  methods: [GET]
```suggestion
  methods: [ GET ]
```

2023-05-15 22:03 UTC, ManulMax commented on src/plugins/orangehrmClaimPlugin/config/routes.yaml
> +  methods: [GET]
```suggestion
 methods: [ GET ]
```

2023-05-16 03:47 UTC, DulsaraNethmin commented on src/client/src/orangehrmClaimPlugin/components/ClaimEmployeeAutocomplete.vue
> +  name: 'ClaimEmployeeAutocomplete',
need to stop suggesting admin's name.

2023-05-17 10:41 UTC, RajithaKumara requested changes

2023-05-17 10:41 UTC, RajithaKumara commented on src/client/src/orangehrmClaimPlugin/components/ClaimActionButtons.vue
> +      navigate('/claim/assignClaim');
Double check back button behaviour

2023-05-17 10:41 UTC, RajithaKumara commented on src/client/src/orangehrmClaimPlugin/pages/assignClaim/AssignClaim.vue
> +      CANCELLED: this.$t('leave.cancelled'),
TODO:: we may have to move these status to `general` language group

2023-05-17 11:18 UTC, RajithaKumara commented
Closing as this code goes in #1690 as well. Nethmin confirmed all changes are there in that PR.
cc @ManulMax

2023-05-17 11:18 UTC, closed without merging