OHRM5X-2186: Add API doc comments
orangehrm/orangehrm pull request #1696
Opened 2023-05-25 03:54 UTC by DulsaraNethmin

2023-06-07 04:35 UTC, RajithaKumara requested changes

2023-06-07 04:35 UTC, RajithaKumara commented on src/plugins/orangehrmRecruitmentPlugin/Api/EmployeeListAPI.php
> +     *     ),
```suggestion
```

2023-07-27 05:00 UTC, ManulMax commented
All the changes here addressed by #1725 . So can close this PR

2023-08-09 03:03 UTC, RajithaKumara commented
Closing as changes moved to #1725

2023-08-09 03:03 UTC, closed without merging