OHRM5X-2218: Make Claim Event/Expense Type editable
orangehrm/orangehrm pull request #1701
Opened 2023-05-29 13:02 UTC by DulsaraNethmin

2023-05-31 04:28 UTC, ManulMax requested changes

2023-05-31 04:44 UTC, RajithaKumara requested changes

2023-05-31 04:44 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +        return $qb->getQuery()->getSingleScalarResult() > 0;
```php
        $qb = $this->createQueryBuilder(ClaimRequest::class, 'claimRequest');
        $qb->andWhere('claimRequest.claimEvent = :eventId');
        $qb->setParameter('eventId', $eventId);
        return $this->getPaginator($qb)->count() > 0;
```
how about this :thinking:

2023-05-31 04:44 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dao/ClaimDao.php
> +        return $qb->getQuery()->getSingleScalarResult() > 0;
```php
        $qb = $this->createQueryBuilder(ClaimExpense::class, 'claimExpense');
        $qb->leftJoin('claimExpense.expenseType', 'expenseType');
        $qb->andWhere('claimExpense.expenseType = :expenseTypeId');
        $qb->setParameter('expenseTypeId', $expenseTypeId);
        return $this->getPaginator($qb)->count() > 0;
```
:thinking:

2023-05-31 04:51 UTC, DulsaraNethmin commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +        }
used to handle situation like, when sending "name" in a request body for used ClaimEvent.

2023-05-31 05:17 UTC, DulsaraNethmin commented on src/plugins/orangehrmClaimPlugin/test/fixtures/testcases/ClaimExpenseTypeAPITestCases.yaml
> +      "canEdit": true,
since it's a getOne, no need total

2023-05-31 06:35 UTC, DulsaraNethmin commented on src/plugins/orangehrmClaimPlugin/Api/ClaimEventAPI.php
> +        if (!$canNameEdit && $name) {
checking is it null or not.

2023-06-01 04:02 UTC, RajithaKumara approved these changes

2023-06-01 04:16 UTC, merged