OHRM5X-2219: Add Include Employee Filter To Employee Claims
orangehrm/orangehrm pull request #1705
Opened 2023-06-05 18:59 UTC by ManulMax

2023-06-05 19:00 UTC, ManulMax commented
**need to add/improve api testing

2023-06-07 04:25 UTC, RajithaKumara requested changes

2023-06-07 04:25 UTC, RajithaKumara commented on src/client/src/core/util/helper/filesize.ts
>  const GIGA_BYTE = 1073741824; // 1024 * 1024 * 1024
```suggestion
const MEGA_BYTE = 1_000_000; // 1000 * 1000
const GIGA_BYTE = 1_000_000_000; // 1000 * 1000 * 1000
```

2023-06-07 04:25 UTC, RajithaKumara commented on src/client/src/core/util/helper/__tests__/filesize.spec.ts
Add few test cases to cover MB and GB

2023-06-07 04:25 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +    public const FILTER_INCLUDE_EMPLOYEES = 'includeEmployees';
```php
    public const MODEL_DEFAULT = 'default';
    public const MODEL_SUMMARY = 'summary';
    public const MODEL_MAP = [
        self::MODEL_DEFAULT => EmployeeClaimRequestModel::class,
        self::MODEL_SUMMARY => ClaimRequestSummaryModel::class,
    ];
    public const FILTER_INCLUDE_EMPLOYEES = 'includeEmployees';
```
move new param down

2023-06-07 04:25 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Api/EmployeeClaimRequestAPI.php
> +     *         @OA\Schema(type="string")
```suggestion
     *         @OA\Schema(type="string", enum=ClaimRequestSearchFilterParams::INCLUDE_EMPLOYEES)
```
OR
```suggestion
     *         @OA\Schema(type="string", enum={"onlyCurrent", "onlyPast", "currentAndPast"})
```

Double check and correct https://github.com/search?q=repo%3Aorangehrm%2Forangehrm%20name%3D%22includeEmployees%22%2C&type=code these places also

2023-06-07 04:25 UTC, RajithaKumara commented on src/plugins/orangehrmClaimPlugin/Dto/ClaimRequestSearchFilterParams.php
>          $this->setSortOrder('DESC');
```suggestion
        $this->setSortOrder(ListSorter::DESCENDING);
```

2023-06-08 04:14 UTC, RajithaKumara approved these changes

2023-06-08 04:19 UTC, merged