Ohrm5 x 116: PIM - JOB: FE
orangehrm/orangehrm pull request #782
Opened 2021-06-03 20:57 UTC by ireshe

Draft UI

2021-06-07 03:47 UTC, Super-Chama requested changes

2021-06-07 03:47 UTC, Super-Chama commented on symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeJob.vue
> +            >Include Employement Contract Details &nbsp;</oxd-text
`&nbsp;` don't use this for space. add a class and use margin.

2021-06-07 03:47 UTC, Super-Chama commented on symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeJob.vue
> +        joinedDate: [
Are these validations correct for date?

2021-06-07 03:47 UTC, Super-Chama commented on symfony/client/src/orangehrmPimPlugin/pages/employee/EmployeeJob.vue
> +                startDate: this.contract.startDate,
Here manually setting the fields are not needed since `this.contract` contains it.

2021-06-09 17:27 UTC, RajithaKumara commented
Closing since merge #791

2021-06-09 17:27 UTC, closed without merging