OHRM5X-123: Qualification Skill BE
orangehrm/orangehrm pull request #783
Opened 2021-06-04 05:55 UTC by KaveeshaSilva1996

2021-06-04 06:42 UTC, KaveeshaSilva1996 commented
Unit tests not covered yet

2021-06-09 09:36 UTC, RajithaKumara requested changes
Good job @KaveeshaSilva1996 seems cover units test for all files

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +        if (!$employeeSkill instanceof EmployeeSkill) {
no need if condition, just use `$this->throwRecordNotFoundExceptionIfNotExist($employeeSkill, EmployeeSkill::class);`

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +            if ($employeeSkill == null) {
remove if condition, just use `$this->throwRecordNotFoundExceptionIfNotExist($employeeSkill, EmployeeSkill::class);`

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +            new Rule(Rules::REQUIRED)
maybe we can remove `new Rule(Rules::REQUIRED)`

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/Model/EmployeeSkillModel.php
> +class EmployeeSkillModel implements Normalizable
refer `symfony/plugins/orangehrmPimPlugin/Api/Model/EmployeeSalaryModel.php`

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/Model/EmployeeSkillModel.php
> +                ['getEmployee', 'getEmpNumber'],
no need empNumber, since define in API meta

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/Model/EmployeeSkillModel.php
> +                ['getSkill', 'getId'],
```php
['getSkill', 'getId'],
['getSkill', 'getName'],

...

$this->setAttributeNames(
    ['skill', 'id'],
    ['skill', 'name'],
```

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/EmployeeSkillDao.php
> +use Doctrine\ORM\QueryBuilder;
remove unnecessary imports

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/EmployeeSkillDao.php
> +use OrangeHRM\ORM\Doctrine;
remove unnecessary imports

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/EmployeeSkillDao.php
> +    private function getSearchEmployeeSkillPaginator(EmployeeSkillSearchFilterParams $employeeSkillSearchParams
do manual formatting if it's ugly
```php
private function getSearchEmployeeSkillPaginator(
EmployeeSkillSearchFilterParams $employeeSkillSearchParams
): 
```

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/EmployeeSkillDao.php
> +        if (!empty($employeeSkillSearchParams->getComments())) {
no need to implement search params for every field, will implement ondemand

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/EmployeeSkillDao.php
> +     * @return array
`@return EmployeeSkill[]`

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/EmployeeSkillDao.php
> +
format the code

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Service/EmployeeSkillService.php
> +    private ?EmployeeSkillDao $EmployeeSkillDao = null;
refactor rename
```php
private ?EmployeeSkillDao $employeeSkillDao = null;
```

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/entity/EmployeeSkill.php
>   * EmployeeSkill
remove entity name

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +                $employeeSkill = $this->getEmployeeSkillService()->getEmployeeSkillDao()->getEmployeeSkillById(
you can fetch before 317 line?

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +            if (!empty($skillId)) {  // create operation
what happen else block of this if

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +                    self::PARAMETER_SKILL_ID => $employeeSkill->getSkill()->getId()
keep `CommonParams::PARAMETER_EMP_NUMBER` in meta, but remove `self::PARAMETER_SKILL_ID` in all Endpoint operations since it should be in Model

2021-06-09 09:36 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +    use EntityManagerHelperTrait;
why here?

2021-06-09 18:38 UTC, KaveeshaSilva1996 commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +    use EntityManagerHelperTrait;
removed

2021-06-09 18:40 UTC, KaveeshaSilva1996 commented on symfony/plugins/orangehrmPimPlugin/Dao/EmployeeSkillDao.php
> +use Doctrine\ORM\QueryBuilder;
removed

2021-06-09 18:40 UTC, KaveeshaSilva1996 commented on symfony/plugins/orangehrmPimPlugin/Dao/EmployeeSkillDao.php
> +use Doctrine\ORM\QueryBuilder;
removed

2021-06-10 06:11 UTC, RajithaKumara requested changes

2021-06-10 06:11 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/EmployeeSkillAPI.php
> +use OrangeHRM\Core\Traits\ORM\EntityManagerHelperTrait;
Remove unnecessary imports

2021-06-10 18:05 UTC, RajithaKumara approved these changes

2021-06-11 10:31 UTC, merged