Test scripts for Skills screen
orangehrm/orangehrm pull request #784
Opened 2021-06-04 07:19 UTC by AshaniUmeendra

Test scripts for Skills screen

2021-06-06 05:41 UTC, samanthajayasinghe commented on symfony/test/functional/cypress/support/index.js
> +require('cypress-xpath')
you may need to update package.json if you need to use this dependency

2021-06-06 05:42 UTC, samanthajayasinghe commented
pls use following format for commit messages 
{OHRM-###} : detailed-message

2021-06-23 08:46 UTC, samanthajayasinghe requested changes

2021-06-23 08:46 UTC, samanthajayasinghe commented on symfony/test/functional/cypress/integration/orangehrm/admin/skills.spec.js
> +        cy.xpath('//body[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/button[2]/i[1]').click()
don't use xpath like this

2021-06-23 08:46 UTC, samanthajayasinghe commented on symfony/test/functional/cypress/integration/orangehrm/admin/skills.spec.js
> +        cy.xpath('//*[@id="app"]/div[1]/div/div[2]/div/div/div[3]/div/div[2]/div[1]/div/div[4]/div/button[1]/i').click()
same here

2021-06-23 08:46 UTC, samanthajayasinghe commented on symfony/test/functional/cypress/integration/orangehrm/admin/skills.spec.js
> +        cy.xpath('//*[@id="app"]/div[1]/div/div[2]/div/div/form/div[2]/div/div[2]/textarea').type('0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
text you can move into fixture file

2021-07-19 17:48 UTC, RajithaKumara commented
Closing since #845

2021-07-19 17:48 UTC, closed without merging