OHRM5X-111: Termination Record FE & BE
orangehrm/orangehrm pull request #819
Opened 2021-06-23 07:20 UTC by ireshe

one test case is failing,
need to check the isReasonInUse DAO function.
need to add Delete warning when deleting the Already in use Termination Record

2021-06-23 08:05 UTC, RajithaKumara requested changes

2021-06-23 08:05 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/TerminationReasonConfigurationDao.php
> +        $query->leftJoin('e.EmployeeTerminationRecord', 'et');
wrong mapping, ==> `e.employeeTerminationRecord `

2021-06-23 08:05 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/TerminationReasonConfigurationDao.php
> +        $query->leftJoin('et.TerminationReason', 'tr')
==> `et.terminationReason`

2021-06-25 07:52 UTC, RajithaKumara requested changes

2021-06-25 07:52 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/TerminationReasonConfigurationDao.php
> +     * @throws NonUniqueResultException
will remove this

2021-06-25 07:52 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Service/TerminationReasonConfigurationService.php
> +    public function isReasonInUse($idArray): bool
```php
public function isReasonInUse(array $idArray): bool
```

2021-06-25 07:52 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/config/routes.yaml
> +  path: /api/v2/pim/termination_records/{id}
`/api/v2/pim/termination-reasons/{id}`

2021-06-25 07:52 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/config/routes.yaml
> +  path: /api/v2/pim/termination_records
`/api/v2/pim/termination-reasons`

2021-06-25 07:52 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/config/routes.yaml
> +apiv2_pim_termination_record:
`apiv2_pim_termination_reason`

2021-06-25 07:52 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/config/routes.yaml
> +apiv2_pim_termination_records:
`apiv2_pim_termination_reasons`

2021-06-25 07:54 UTC, Super-Chama requested changes
Please run `yarn lint` or pretteir format and reformat the code. found many lint issues.

2021-06-25 07:54 UTC, Super-Chama commented on symfony/client/src/orangehrmPimPlugin/pages/configuration/EditTerminationReason.vue
> +      <oxd-text tag="h6">Edit Termination Reason</oxd-text>
Please use class `orangehrm-main-title` for headings.

2021-06-25 07:54 UTC, Super-Chama commented on symfony/client/src/orangehrmPimPlugin/pages/configuration/SaveTerminationReason.vue
> +      <oxd-text tag="h6">Add Termination Reason</oxd-text>
Please use class `orangehrm-main-title` for headings.

2021-06-25 07:54 UTC, Super-Chama commented on symfony/client/src/orangehrmPimPlugin/pages/configuration/TerminationReason.vue
> +        <oxd-text tag="h6">Termination Reasons</oxd-text>
Please use class `orangehrm-main-title` for headings.

2021-06-25 07:54 UTC, Super-Chama commented on symfony/client/src/pages.ts
> +import TerminationReason from '@/orangehrmPimPlugin/pages/configuration/TerminationReason.vue';
`orangehrmPimPlugin` has index.ts files, you should import these files there. it will be automatically added here.

2021-06-25 13:15 UTC, RajithaKumara requested changes

2021-06-25 13:15 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Controller/SaveTerminationReasonController.php
> +    use ConfigServiceTrait;
any reason to use `ConfigServiceTrait`

2021-06-25 13:15 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/config/routes.yaml
> +view_termination_record:
`view_termination_reason`
fix all below keys

2021-06-25 13:17 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Dao/TerminationReasonConfigurationDao.php
> +    public function isExistingTerminationReasonName($terminationReasonName): bool
parameter type for `$terminationReasonName`

2021-06-28 03:58 UTC, merged