OHRM5X-111: Stop deleting the already in use termination Record
orangehrm/orangehrm pull request #829
Opened 2021-07-02 03:01 UTC by ireshe

changed the termination Record screen,
changes the DAO layer and added reasonInUse function,
add validation rule to the API

2021-07-02 03:29 UTC, Super-Chama approved these changes

2021-07-02 06:27 UTC, RajithaKumara requested changes

2021-07-02 06:27 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Api/TerminationReasonConfigurationAPI.php
> +        $isinuse = $this->getTerminationReasonConfigurationService()->reasonInUse();
refactor variable and method
```php
$reasonIdsInUse = $this->getTerminationReasonConfigurationService()->getReasonIdsInUse();
```

2021-07-02 06:27 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Controller/TerminationReasonController.php
> +    protected function getTerminationReasonService(): TerminationReasonConfigurationService
doc comment

2021-07-02 06:27 UTC, RajithaKumara commented on symfony/plugins/orangehrmPimPlugin/Controller/TerminationReasonController.php
> +        $reasonesInUse = $this->getTerminationReasonService()->reasonInUse();
refactor `reasonInUse`

2021-07-07 03:55 UTC, RajithaKumara commented
Closing since moved to #831

2021-07-07 03:55 UTC, closed without merging