OHRM5X-271 : Test script for Skills screen
orangehrm/orangehrm pull request #845
Opened 2021-07-17 07:22 UTC by ShenaliFernando

2021-07-17 10:12 UTC, samanthajayasinghe commented
@ShenaliFernando There are some conflicts in this PR

2021-07-20 03:24 UTC, RajithaKumara requested changes

2021-07-20 03:24 UTC, RajithaKumara commented on symfony/test/functional/cypress/integration/orangehrm/admin/skills.spec.js
> +<<<<<<< e0e330c4cc79b7dc0e369215f90e5aad5e705f8a
resolve this conflict

2021-07-20 03:24 UTC, RajithaKumara commented on symfony/test/functional/cypress/fixtures/admin.json
> +}
add new line

2021-07-20 03:24 UTC, RajithaKumara commented on symfony/test/functional/cypress.json
> +    "baseUrl": "http://php80/orangehrm/symfony/web/index.php",
revert this change

2021-07-20 08:44 UTC, ShenaliFernando commented on symfony/test/functional/cypress/fixtures/admin.json
> +}
New line added

2021-07-29 10:33 UTC, ShenaliFernando commented on symfony/test/functional/cypress.json
> +    "baseUrl": "http://php80/orangehrm/symfony/web/index.php",
Done

2021-08-02 08:31 UTC, samanthajayasinghe approved these changes

2021-08-02 08:31 UTC, merged